# syntax=docker/dockerfile:1
FROM python:3.13-slim-bookworm
LABEL piwork.file_protocol="1"
ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR /opt/piwork/file-helper
COPY apps/file-helper/*.py ./
USER 10001:10001
ENTRYPOINT ["python3", "-B", "/opt/piwork/file-helper/main.py"]
