// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.36.2
// source: work-services.proto

package servicesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	ModelProviderContractVersion *uint32                `protobuf:"varint,1,opt,name=model_provider_contract_version,json=modelProviderContractVersion,proto3,oneof" json:"model_provider_contract_version,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_work_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{0}
}

func (x *Empty) GetModelProviderContractVersion() uint32 {
	if x != nil && x.ModelProviderContractVersion != nil {
		return *x.ModelProviderContractVersion
	}
	return 0
}

// Authenticated only through the current agentd runtime mTLS identity.
type WorkPrivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputJson     string                 `protobuf:"bytes,1,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkPrivateRequest) Reset() {
	*x = WorkPrivateRequest{}
	mi := &file_work_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkPrivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkPrivateRequest) ProtoMessage() {}

func (x *WorkPrivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkPrivateRequest.ProtoReflect.Descriptor instead.
func (*WorkPrivateRequest) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{1}
}

func (x *WorkPrivateRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type WorkPrivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValueJson     string                 `protobuf:"bytes,1,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkPrivateResponse) Reset() {
	*x = WorkPrivateResponse{}
	mi := &file_work_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkPrivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkPrivateResponse) ProtoMessage() {}

func (x *WorkPrivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkPrivateResponse.ProtoReflect.Descriptor instead.
func (*WorkPrivateResponse) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{2}
}

func (x *WorkPrivateResponse) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

type RunModelResolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelJson     string                 `protobuf:"bytes,1,opt,name=model_json,json=modelJson,proto3" json:"model_json,omitempty"`
	Credential    string                 `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunModelResolution) Reset() {
	*x = RunModelResolution{}
	mi := &file_work_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunModelResolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunModelResolution) ProtoMessage() {}

func (x *RunModelResolution) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunModelResolution.ProtoReflect.Descriptor instead.
func (*RunModelResolution) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{3}
}

func (x *RunModelResolution) GetModelJson() string {
	if x != nil {
		return x.ModelJson
	}
	return ""
}

func (x *RunModelResolution) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type ServiceImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceImage) Reset() {
	*x = ServiceImage{}
	mi := &file_work_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceImage) ProtoMessage() {}

func (x *ServiceImage) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceImage.ProtoReflect.Descriptor instead.
func (*ServiceImage) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceImage) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type ServiceMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceMount) Reset() {
	*x = ServiceMount{}
	mi := &file_work_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMount) ProtoMessage() {}

func (x *ServiceMount) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMount.ProtoReflect.Descriptor instead.
func (*ServiceMount) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ServiceMount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ServiceMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type ServicePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContainerPort uint32                 `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePort) Reset() {
	*x = ServicePort{}
	mi := &file_work_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePort) ProtoMessage() {}

func (x *ServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePort.ProtoReflect.Descriptor instead.
func (*ServicePort) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{6}
}

func (x *ServicePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServicePort) GetContainerPort() uint32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *ServicePort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ReadinessProbe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	PortName      string                 `protobuf:"bytes,2,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Command       []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	DeadlineMs    uint32                 `protobuf:"varint,5,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessProbe) Reset() {
	*x = ReadinessProbe{}
	mi := &file_work_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessProbe) ProtoMessage() {}

func (x *ReadinessProbe) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessProbe.ProtoReflect.Descriptor instead.
func (*ReadinessProbe) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{7}
}

func (x *ReadinessProbe) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ReadinessProbe) GetPortName() string {
	if x != nil {
		return x.PortName
	}
	return ""
}

func (x *ReadinessProbe) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadinessProbe) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ReadinessProbe) GetDeadlineMs() uint32 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *ReadinessProbe) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ServiceDefinition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image            *ServiceImage          `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Command          string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Args             []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Environment      map[string]string      `protobuf:"bytes,5,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SecretRefs       []string               `protobuf:"bytes,6,rep,name=secret_refs,json=secretRefs,proto3" json:"secret_refs,omitempty"`
	WorkingDirectory string                 `protobuf:"bytes,7,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	Mounts           []*ServiceMount        `protobuf:"bytes,8,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Ports            []*ServicePort         `protobuf:"bytes,9,rep,name=ports,proto3" json:"ports,omitempty"`
	CpuMillis        uint32                 `protobuf:"varint,10,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	MemoryBytes      uint64                 `protobuf:"varint,11,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Enabled          bool                   `protobuf:"varint,12,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Required         bool                   `protobuf:"varint,13,opt,name=required,proto3" json:"required,omitempty"`
	Readiness        *ReadinessProbe        `protobuf:"bytes,14,opt,name=readiness,proto3,oneof" json:"readiness,omitempty"`
	RestartPolicy    string                 `protobuf:"bytes,15,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceDefinition) Reset() {
	*x = ServiceDefinition{}
	mi := &file_work_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDefinition) ProtoMessage() {}

func (x *ServiceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDefinition.ProtoReflect.Descriptor instead.
func (*ServiceDefinition) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceDefinition) GetImage() *ServiceImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ServiceDefinition) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ServiceDefinition) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ServiceDefinition) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ServiceDefinition) GetSecretRefs() []string {
	if x != nil {
		return x.SecretRefs
	}
	return nil
}

func (x *ServiceDefinition) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *ServiceDefinition) GetMounts() []*ServiceMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *ServiceDefinition) GetPorts() []*ServicePort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ServiceDefinition) GetCpuMillis() uint32 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

func (x *ServiceDefinition) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ServiceDefinition) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServiceDefinition) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ServiceDefinition) GetReadiness() *ReadinessProbe {
	if x != nil {
		return x.Readiness
	}
	return nil
}

func (x *ServiceDefinition) GetRestartPolicy() string {
	if x != nil {
		return x.RestartPolicy
	}
	return ""
}

type ServiceEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEndpoint) Reset() {
	*x = ServiceEndpoint{}
	mi := &file_work_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEndpoint) ProtoMessage() {}

func (x *ServiceEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEndpoint.ProtoReflect.Descriptor instead.
func (*ServiceEndpoint) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceEndpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceEndpoint) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ServiceEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServiceEndpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceEndpoint) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ServiceAccessPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAccessPort) Reset() {
	*x = ServiceAccessPort{}
	mi := &file_work_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccessPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccessPort) ProtoMessage() {}

func (x *ServiceAccessPort) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccessPort.ProtoReflect.Descriptor instead.
func (*ServiceAccessPort) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceAccessPort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAccessPort) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceAccessPort) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ServiceAccess struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	DefaultUrl      *string                `protobuf:"bytes,2,opt,name=default_url,json=defaultUrl,proto3,oneof" json:"default_url,omitempty"`
	DefaultPortName *string                `protobuf:"bytes,3,opt,name=default_port_name,json=defaultPortName,proto3,oneof" json:"default_port_name,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Ports           []*ServiceAccessPort   `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceAccess) Reset() {
	*x = ServiceAccess{}
	mi := &file_work_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccess) ProtoMessage() {}

func (x *ServiceAccess) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccess.ProtoReflect.Descriptor instead.
func (*ServiceAccess) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceAccess) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ServiceAccess) GetDefaultUrl() string {
	if x != nil && x.DefaultUrl != nil {
		return *x.DefaultUrl
	}
	return ""
}

func (x *ServiceAccess) GetDefaultPortName() string {
	if x != nil && x.DefaultPortName != nil {
		return *x.DefaultPortName
	}
	return ""
}

func (x *ServiceAccess) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceAccess) GetPorts() []*ServiceAccessPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

type SafeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Remediation   string                 `protobuf:"bytes,4,opt,name=remediation,proto3" json:"remediation,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SafeError) Reset() {
	*x = SafeError{}
	mi := &file_work_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeError) ProtoMessage() {}

func (x *SafeError) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeError.ProtoReflect.Descriptor instead.
func (*SafeError) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{12}
}

func (x *SafeError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SafeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SafeError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SafeError) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

func (x *SafeError) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ServiceView struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkId          string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	ServiceId       string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DesiredRevision uint32                 `protobuf:"varint,4,opt,name=desired_revision,json=desiredRevision,proto3" json:"desired_revision,omitempty"`
	AppliedRevision *uint32                `protobuf:"varint,5,opt,name=applied_revision,json=appliedRevision,proto3,oneof" json:"applied_revision,omitempty"`
	Enabled         bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ObservedState   string                 `protobuf:"bytes,7,opt,name=observed_state,json=observedState,proto3" json:"observed_state,omitempty"`
	Definition      *ServiceDefinition     `protobuf:"bytes,8,opt,name=definition,proto3" json:"definition,omitempty"`
	Endpoints       []*ServiceEndpoint     `protobuf:"bytes,9,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	LastError       *SafeError             `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3,oneof" json:"last_error,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Access          *ServiceAccess         `protobuf:"bytes,12,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceView) Reset() {
	*x = ServiceView{}
	mi := &file_work_services_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceView) ProtoMessage() {}

func (x *ServiceView) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceView.ProtoReflect.Descriptor instead.
func (*ServiceView) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{13}
}

func (x *ServiceView) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *ServiceView) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceView) GetDesiredRevision() uint32 {
	if x != nil {
		return x.DesiredRevision
	}
	return 0
}

func (x *ServiceView) GetAppliedRevision() uint32 {
	if x != nil && x.AppliedRevision != nil {
		return *x.AppliedRevision
	}
	return 0
}

func (x *ServiceView) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServiceView) GetObservedState() string {
	if x != nil {
		return x.ObservedState
	}
	return ""
}

func (x *ServiceView) GetDefinition() *ServiceDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *ServiceView) GetEndpoints() []*ServiceEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ServiceView) GetLastError() *SafeError {
	if x != nil {
		return x.LastError
	}
	return nil
}

func (x *ServiceView) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ServiceView) GetAccess() *ServiceAccess {
	if x != nil {
		return x.Access
	}
	return nil
}

type OperationView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	WorkId        string                 `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Error         *SafeError             `protobuf:"bytes,8,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationView) Reset() {
	*x = OperationView{}
	mi := &file_work_services_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationView) ProtoMessage() {}

func (x *OperationView) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationView.ProtoReflect.Descriptor instead.
func (*OperationView) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{14}
}

func (x *OperationView) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationView) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *OperationView) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *OperationView) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OperationView) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OperationView) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OperationView) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *OperationView) GetError() *SafeError {
	if x != nil {
		return x.Error
	}
	return nil
}

type Acceptance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Reused        bool                   `protobuf:"varint,3,opt,name=reused,proto3" json:"reused,omitempty"`
	WorkId        string                 `protobuf:"bytes,4,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acceptance) Reset() {
	*x = Acceptance{}
	mi := &file_work_services_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acceptance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acceptance) ProtoMessage() {}

func (x *Acceptance) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acceptance.ProtoReflect.Descriptor instead.
func (*Acceptance) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{15}
}

func (x *Acceptance) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Acceptance) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Acceptance) GetReused() bool {
	if x != nil {
		return x.Reused
	}
	return false
}

func (x *Acceptance) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *Acceptance) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type DeploymentContext struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	WorkId                    string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	WorkspacePath             string                 `protobuf:"bytes,2,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
	WorkspaceWritable         bool                   `protobuf:"varint,3,opt,name=workspace_writable,json=workspaceWritable,proto3" json:"workspace_writable,omitempty"`
	Lifecycle                 string                 `protobuf:"bytes,4,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	TotalCpuMillis            uint32                 `protobuf:"varint,5,opt,name=total_cpu_millis,json=totalCpuMillis,proto3" json:"total_cpu_millis,omitempty"`
	TotalMemoryBytes          uint64                 `protobuf:"varint,6,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"`
	AgentCpuMillis            uint32                 `protobuf:"varint,7,opt,name=agent_cpu_millis,json=agentCpuMillis,proto3" json:"agent_cpu_millis,omitempty"`
	AgentMemoryBytes          uint64                 `protobuf:"varint,8,opt,name=agent_memory_bytes,json=agentMemoryBytes,proto3" json:"agent_memory_bytes,omitempty"`
	AvailableCpuMillis        uint32                 `protobuf:"varint,9,opt,name=available_cpu_millis,json=availableCpuMillis,proto3" json:"available_cpu_millis,omitempty"`
	AvailableMemoryBytes      uint64                 `protobuf:"varint,10,opt,name=available_memory_bytes,json=availableMemoryBytes,proto3" json:"available_memory_bytes,omitempty"`
	DefaultServiceCpuMillis   uint32                 `protobuf:"varint,11,opt,name=default_service_cpu_millis,json=defaultServiceCpuMillis,proto3" json:"default_service_cpu_millis,omitempty"`
	DefaultServiceMemoryBytes uint64                 `protobuf:"varint,12,opt,name=default_service_memory_bytes,json=defaultServiceMemoryBytes,proto3" json:"default_service_memory_bytes,omitempty"`
	ApiVersion                string                 `protobuf:"bytes,13,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DeploymentContext) Reset() {
	*x = DeploymentContext{}
	mi := &file_work_services_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentContext) ProtoMessage() {}

func (x *DeploymentContext) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentContext.ProtoReflect.Descriptor instead.
func (*DeploymentContext) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{16}
}

func (x *DeploymentContext) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *DeploymentContext) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

func (x *DeploymentContext) GetWorkspaceWritable() bool {
	if x != nil {
		return x.WorkspaceWritable
	}
	return false
}

func (x *DeploymentContext) GetLifecycle() string {
	if x != nil {
		return x.Lifecycle
	}
	return ""
}

func (x *DeploymentContext) GetTotalCpuMillis() uint32 {
	if x != nil {
		return x.TotalCpuMillis
	}
	return 0
}

func (x *DeploymentContext) GetTotalMemoryBytes() uint64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

func (x *DeploymentContext) GetAgentCpuMillis() uint32 {
	if x != nil {
		return x.AgentCpuMillis
	}
	return 0
}

func (x *DeploymentContext) GetAgentMemoryBytes() uint64 {
	if x != nil {
		return x.AgentMemoryBytes
	}
	return 0
}

func (x *DeploymentContext) GetAvailableCpuMillis() uint32 {
	if x != nil {
		return x.AvailableCpuMillis
	}
	return 0
}

func (x *DeploymentContext) GetAvailableMemoryBytes() uint64 {
	if x != nil {
		return x.AvailableMemoryBytes
	}
	return 0
}

func (x *DeploymentContext) GetDefaultServiceCpuMillis() uint32 {
	if x != nil {
		return x.DefaultServiceCpuMillis
	}
	return 0
}

func (x *DeploymentContext) GetDefaultServiceMemoryBytes() uint64 {
	if x != nil {
		return x.DefaultServiceMemoryBytes
	}
	return 0
}

func (x *DeploymentContext) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type CreateServiceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Definition     *ServiceDefinition     `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_work_services_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{17}
}

func (x *CreateServiceRequest) GetDefinition() *ServiceDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *CreateServiceRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceView         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_work_services_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{18}
}

func (x *ListServicesResponse) GetServices() []*ServiceView {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceIdRequest) Reset() {
	*x = ServiceIdRequest{}
	mi := &file_work_services_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceIdRequest) ProtoMessage() {}

func (x *ServiceIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceIdRequest.ProtoReflect.Descriptor instead.
func (*ServiceIdRequest) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{19}
}

func (x *ServiceIdRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type MutateServiceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceId      string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MutateServiceRequest) Reset() {
	*x = MutateServiceRequest{}
	mi := &file_work_services_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateServiceRequest) ProtoMessage() {}

func (x *MutateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateServiceRequest.ProtoReflect.Descriptor instead.
func (*MutateServiceRequest) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{20}
}

func (x *MutateServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *MutateServiceRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UpdateServiceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceId        string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ExpectedRevision uint32                 `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	Definition       *ServiceDefinition     `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_work_services_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *UpdateServiceRequest) GetExpectedRevision() uint32 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *UpdateServiceRequest) GetDefinition() *ServiceDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *UpdateServiceRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type OperationIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationIdRequest) Reset() {
	*x = OperationIdRequest{}
	mi := &file_work_services_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationIdRequest) ProtoMessage() {}

func (x *OperationIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationIdRequest.ProtoReflect.Descriptor instead.
func (*OperationIdRequest) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{22}
}

func (x *OperationIdRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type ReadServiceLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	TailLines     uint32                 `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadServiceLogsRequest) Reset() {
	*x = ReadServiceLogsRequest{}
	mi := &file_work_services_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadServiceLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadServiceLogsRequest) ProtoMessage() {}

func (x *ReadServiceLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadServiceLogsRequest.ProtoReflect.Descriptor instead.
func (*ReadServiceLogsRequest) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{23}
}

func (x *ReadServiceLogsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ReadServiceLogsRequest) GetTailLines() uint32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

type ServiceLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Truncated     bool                   `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"`
	CollectedAt   string                 `protobuf:"bytes,5,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	Error         *SafeError             `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceLogs) Reset() {
	*x = ServiceLogs{}
	mi := &file_work_services_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLogs) ProtoMessage() {}

func (x *ServiceLogs) ProtoReflect() protoreflect.Message {
	mi := &file_work_services_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLogs.ProtoReflect.Descriptor instead.
func (*ServiceLogs) Descriptor() ([]byte, []int) {
	return file_work_services_proto_rawDescGZIP(), []int{24}
}

func (x *ServiceLogs) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceLogs) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceLogs) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ServiceLogs) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ServiceLogs) GetCollectedAt() string {
	if x != nil {
		return x.CollectedAt
	}
	return ""
}

func (x *ServiceLogs) GetError() *SafeError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_work_services_proto protoreflect.FileDescriptor

const file_work_services_proto_rawDesc = "" +
	"\n" +
	"\x13work-services.proto\x12\x17piwork.core.services.v1\"w\n" +
	"\x05Empty\x12J\n" +
	"\x1fmodel_provider_contract_version\x18\x01 \x01(\rH\x00R\x1cmodelProviderContractVersion\x88\x01\x01B\"\n" +
	" _model_provider_contract_version\"3\n" +
	"\x12WorkPrivateRequest\x12\x1d\n" +
	"\n" +
	"input_json\x18\x01 \x01(\tR\tinputJson\"4\n" +
	"\x13WorkPrivateResponse\x12\x1d\n" +
	"\n" +
	"value_json\x18\x01 \x01(\tR\tvalueJson\"S\n" +
	"\x12RunModelResolution\x12\x1d\n" +
	"\n" +
	"model_json\x18\x01 \x01(\tR\tmodelJson\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\tR\n" +
	"credential\",\n" +
	"\fServiceImage\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\"[\n" +
	"\fServiceMount\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"d\n" +
	"\vServicePort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\rR\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xaf\x01\n" +
	"\x0eReadinessProbe\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1b\n" +
	"\tport_name\x18\x02 \x01(\tR\bportName\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12\x1f\n" +
	"\vdeadline_ms\x18\x05 \x01(\rR\n" +
	"deadlineMs\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\rR\ttimeoutMs\"\xf3\x05\n" +
	"\x11ServiceDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\x05image\x18\x02 \x01(\v2%.piwork.core.services.v1.ServiceImageR\x05image\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12]\n" +
	"\venvironment\x18\x05 \x03(\v2;.piwork.core.services.v1.ServiceDefinition.EnvironmentEntryR\venvironment\x12\x1f\n" +
	"\vsecret_refs\x18\x06 \x03(\tR\n" +
	"secretRefs\x12+\n" +
	"\x11working_directory\x18\a \x01(\tR\x10workingDirectory\x12=\n" +
	"\x06mounts\x18\b \x03(\v2%.piwork.core.services.v1.ServiceMountR\x06mounts\x12:\n" +
	"\x05ports\x18\t \x03(\v2$.piwork.core.services.v1.ServicePortR\x05ports\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\n" +
	" \x01(\rR\tcpuMillis\x12!\n" +
	"\fmemory_bytes\x18\v \x01(\x04R\vmemoryBytes\x12\x18\n" +
	"\aenabled\x18\f \x01(\bR\aenabled\x12\x1a\n" +
	"\brequired\x18\r \x01(\bR\brequired\x12J\n" +
	"\treadiness\x18\x0e \x01(\v2'.piwork.core.services.v1.ReadinessProbeH\x00R\treadiness\x88\x01\x01\x12%\n" +
	"\x0erestart_policy\x18\x0f \x01(\tR\rrestartPolicy\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_readiness\"{\n" +
	"\x0fServiceEndpoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"M\n" +
	"\x11ServiceAccessPort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x82\x02\n" +
	"\rServiceAccess\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12$\n" +
	"\vdefault_url\x18\x02 \x01(\tH\x00R\n" +
	"defaultUrl\x88\x01\x01\x12/\n" +
	"\x11default_port_name\x18\x03 \x01(\tH\x01R\x0fdefaultPortName\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12@\n" +
	"\x05ports\x18\x05 \x03(\v2*.piwork.core.services.v1.ServiceAccessPortR\x05portsB\x0e\n" +
	"\f_default_urlB\x14\n" +
	"\x12_default_port_name\"\x98\x01\n" +
	"\tSafeError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\x12 \n" +
	"\vremediation\x18\x04 \x01(\tR\vremediation\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\xd4\x04\n" +
	"\vServiceView\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12)\n" +
	"\x10desired_revision\x18\x04 \x01(\rR\x0fdesiredRevision\x12.\n" +
	"\x10applied_revision\x18\x05 \x01(\rH\x00R\x0fappliedRevision\x88\x01\x01\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12%\n" +
	"\x0eobserved_state\x18\a \x01(\tR\robservedState\x12J\n" +
	"\n" +
	"definition\x18\b \x01(\v2*.piwork.core.services.v1.ServiceDefinitionR\n" +
	"definition\x12F\n" +
	"\tendpoints\x18\t \x03(\v2(.piwork.core.services.v1.ServiceEndpointR\tendpoints\x12F\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\v2\".piwork.core.services.v1.SafeErrorH\x01R\tlastError\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12>\n" +
	"\x06access\x18\f \x01(\v2&.piwork.core.services.v1.ServiceAccessR\x06accessB\x13\n" +
	"\x11_applied_revisionB\r\n" +
	"\v_last_error\"\x9b\x02\n" +
	"\rOperationView\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12=\n" +
	"\x05error\x18\b \x01(\v2\".piwork.core.services.v1.SafeErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xa6\x01\n" +
	"\n" +
	"Acceptance\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x16\n" +
	"\x06reused\x18\x03 \x01(\bR\x06reused\x12\x17\n" +
	"\awork_id\x18\x04 \x01(\tR\x06workId\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\xd7\x04\n" +
	"\x11DeploymentContext\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12%\n" +
	"\x0eworkspace_path\x18\x02 \x01(\tR\rworkspacePath\x12-\n" +
	"\x12workspace_writable\x18\x03 \x01(\bR\x11workspaceWritable\x12\x1c\n" +
	"\tlifecycle\x18\x04 \x01(\tR\tlifecycle\x12(\n" +
	"\x10total_cpu_millis\x18\x05 \x01(\rR\x0etotalCpuMillis\x12,\n" +
	"\x12total_memory_bytes\x18\x06 \x01(\x04R\x10totalMemoryBytes\x12(\n" +
	"\x10agent_cpu_millis\x18\a \x01(\rR\x0eagentCpuMillis\x12,\n" +
	"\x12agent_memory_bytes\x18\b \x01(\x04R\x10agentMemoryBytes\x120\n" +
	"\x14available_cpu_millis\x18\t \x01(\rR\x12availableCpuMillis\x124\n" +
	"\x16available_memory_bytes\x18\n" +
	" \x01(\x04R\x14availableMemoryBytes\x12;\n" +
	"\x1adefault_service_cpu_millis\x18\v \x01(\rR\x17defaultServiceCpuMillis\x12?\n" +
	"\x1cdefault_service_memory_bytes\x18\f \x01(\x04R\x19defaultServiceMemoryBytes\x12\x1f\n" +
	"\vapi_version\x18\r \x01(\tR\n" +
	"apiVersion\"\x8b\x01\n" +
	"\x14CreateServiceRequest\x12J\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2*.piwork.core.services.v1.ServiceDefinitionR\n" +
	"definition\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"X\n" +
	"\x14ListServicesResponse\x12@\n" +
	"\bservices\x18\x01 \x03(\v2$.piwork.core.services.v1.ServiceViewR\bservices\"1\n" +
	"\x10ServiceIdRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"^\n" +
	"\x14MutateServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"\xd7\x01\n" +
	"\x14UpdateServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\rR\x10expectedRevision\x12J\n" +
	"\n" +
	"definition\x18\x03 \x01(\v2*.piwork.core.services.v1.ServiceDefinitionR\n" +
	"definition\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"7\n" +
	"\x12OperationIdRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"V\n" +
	"\x16ReadServiceLogsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\rR\ttailLines\"\xe2\x01\n" +
	"\vServiceLogs\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1c\n" +
	"\ttruncated\x18\x04 \x01(\bR\ttruncated\x12!\n" +
	"\fcollected_at\x18\x05 \x01(\tR\vcollectedAt\x12=\n" +
	"\x05error\x18\x06 \x01(\v2\".piwork.core.services.v1.SafeErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xdb\x0e\n" +
	"\fWorkServices\x12]\n" +
	"\rListRunModels\x12\x1e.piwork.core.services.v1.Empty\x1a,.piwork.core.services.v1.WorkPrivateResponse\x12k\n" +
	"\x0fResolveRunModel\x12+.piwork.core.services.v1.WorkPrivateRequest\x1a+.piwork.core.services.v1.RunModelResolution\x12m\n" +
	"\x1dGetServiceInteractionBindings\x12\x1e.piwork.core.services.v1.Empty\x1a,.piwork.core.services.v1.WorkPrivateResponse\x12r\n" +
	"\x15PrepareBrainCandidate\x12+.piwork.core.services.v1.WorkPrivateRequest\x1a,.piwork.core.services.v1.WorkPrivateResponse\x12s\n" +
	"\x16GetBrainCandidateState\x12+.piwork.core.services.v1.WorkPrivateRequest\x1a,.piwork.core.services.v1.WorkPrivateResponse\x12v\n" +
	"\x19AuthorizeHistoryMigration\x12+.piwork.core.services.v1.WorkPrivateRequest\x1a,.piwork.core.services.v1.WorkPrivateResponse\x12b\n" +
	"\x14GetDeploymentContext\x12\x1e.piwork.core.services.v1.Empty\x1a*.piwork.core.services.v1.DeploymentContext\x12c\n" +
	"\rCreateService\x12-.piwork.core.services.v1.CreateServiceRequest\x1a#.piwork.core.services.v1.Acceptance\x12]\n" +
	"\fListServices\x12\x1e.piwork.core.services.v1.Empty\x1a-.piwork.core.services.v1.ListServicesResponse\x12]\n" +
	"\n" +
	"GetService\x12).piwork.core.services.v1.ServiceIdRequest\x1a$.piwork.core.services.v1.ServiceView\x12c\n" +
	"\rUpdateService\x12-.piwork.core.services.v1.UpdateServiceRequest\x1a#.piwork.core.services.v1.Acceptance\x12b\n" +
	"\fStartService\x12-.piwork.core.services.v1.MutateServiceRequest\x1a#.piwork.core.services.v1.Acceptance\x12a\n" +
	"\vStopService\x12-.piwork.core.services.v1.MutateServiceRequest\x1a#.piwork.core.services.v1.Acceptance\x12d\n" +
	"\x0eRestartService\x12-.piwork.core.services.v1.MutateServiceRequest\x1a#.piwork.core.services.v1.Acceptance\x12c\n" +
	"\rRemoveService\x12-.piwork.core.services.v1.MutateServiceRequest\x1a#.piwork.core.services.v1.Acceptance\x12b\n" +
	"\fRetryService\x12-.piwork.core.services.v1.MutateServiceRequest\x1a#.piwork.core.services.v1.Acceptance\x12c\n" +
	"\fGetOperation\x12+.piwork.core.services.v1.OperationIdRequest\x1a&.piwork.core.services.v1.OperationView\x12h\n" +
	"\x0fReadServiceLogs\x12/.piwork.core.services.v1.ReadServiceLogsRequest\x1a$.piwork.core.services.v1.ServiceLogsb\x06proto3"

var (
	file_work_services_proto_rawDescOnce sync.Once
	file_work_services_proto_rawDescData []byte
)

func file_work_services_proto_rawDescGZIP() []byte {
	file_work_services_proto_rawDescOnce.Do(func() {
		file_work_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_work_services_proto_rawDesc), len(file_work_services_proto_rawDesc)))
	})
	return file_work_services_proto_rawDescData
}

var file_work_services_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_work_services_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: piwork.core.services.v1.Empty
	(*WorkPrivateRequest)(nil),     // 1: piwork.core.services.v1.WorkPrivateRequest
	(*WorkPrivateResponse)(nil),    // 2: piwork.core.services.v1.WorkPrivateResponse
	(*RunModelResolution)(nil),     // 3: piwork.core.services.v1.RunModelResolution
	(*ServiceImage)(nil),           // 4: piwork.core.services.v1.ServiceImage
	(*ServiceMount)(nil),           // 5: piwork.core.services.v1.ServiceMount
	(*ServicePort)(nil),            // 6: piwork.core.services.v1.ServicePort
	(*ReadinessProbe)(nil),         // 7: piwork.core.services.v1.ReadinessProbe
	(*ServiceDefinition)(nil),      // 8: piwork.core.services.v1.ServiceDefinition
	(*ServiceEndpoint)(nil),        // 9: piwork.core.services.v1.ServiceEndpoint
	(*ServiceAccessPort)(nil),      // 10: piwork.core.services.v1.ServiceAccessPort
	(*ServiceAccess)(nil),          // 11: piwork.core.services.v1.ServiceAccess
	(*SafeError)(nil),              // 12: piwork.core.services.v1.SafeError
	(*ServiceView)(nil),            // 13: piwork.core.services.v1.ServiceView
	(*OperationView)(nil),          // 14: piwork.core.services.v1.OperationView
	(*Acceptance)(nil),             // 15: piwork.core.services.v1.Acceptance
	(*DeploymentContext)(nil),      // 16: piwork.core.services.v1.DeploymentContext
	(*CreateServiceRequest)(nil),   // 17: piwork.core.services.v1.CreateServiceRequest
	(*ListServicesResponse)(nil),   // 18: piwork.core.services.v1.ListServicesResponse
	(*ServiceIdRequest)(nil),       // 19: piwork.core.services.v1.ServiceIdRequest
	(*MutateServiceRequest)(nil),   // 20: piwork.core.services.v1.MutateServiceRequest
	(*UpdateServiceRequest)(nil),   // 21: piwork.core.services.v1.UpdateServiceRequest
	(*OperationIdRequest)(nil),     // 22: piwork.core.services.v1.OperationIdRequest
	(*ReadServiceLogsRequest)(nil), // 23: piwork.core.services.v1.ReadServiceLogsRequest
	(*ServiceLogs)(nil),            // 24: piwork.core.services.v1.ServiceLogs
	nil,                            // 25: piwork.core.services.v1.ServiceDefinition.EnvironmentEntry
}
var file_work_services_proto_depIdxs = []int32{
	4,  // 0: piwork.core.services.v1.ServiceDefinition.image:type_name -> piwork.core.services.v1.ServiceImage
	25, // 1: piwork.core.services.v1.ServiceDefinition.environment:type_name -> piwork.core.services.v1.ServiceDefinition.EnvironmentEntry
	5,  // 2: piwork.core.services.v1.ServiceDefinition.mounts:type_name -> piwork.core.services.v1.ServiceMount
	6,  // 3: piwork.core.services.v1.ServiceDefinition.ports:type_name -> piwork.core.services.v1.ServicePort
	7,  // 4: piwork.core.services.v1.ServiceDefinition.readiness:type_name -> piwork.core.services.v1.ReadinessProbe
	10, // 5: piwork.core.services.v1.ServiceAccess.ports:type_name -> piwork.core.services.v1.ServiceAccessPort
	8,  // 6: piwork.core.services.v1.ServiceView.definition:type_name -> piwork.core.services.v1.ServiceDefinition
	9,  // 7: piwork.core.services.v1.ServiceView.endpoints:type_name -> piwork.core.services.v1.ServiceEndpoint
	12, // 8: piwork.core.services.v1.ServiceView.last_error:type_name -> piwork.core.services.v1.SafeError
	11, // 9: piwork.core.services.v1.ServiceView.access:type_name -> piwork.core.services.v1.ServiceAccess
	12, // 10: piwork.core.services.v1.OperationView.error:type_name -> piwork.core.services.v1.SafeError
	8,  // 11: piwork.core.services.v1.CreateServiceRequest.definition:type_name -> piwork.core.services.v1.ServiceDefinition
	13, // 12: piwork.core.services.v1.ListServicesResponse.services:type_name -> piwork.core.services.v1.ServiceView
	8,  // 13: piwork.core.services.v1.UpdateServiceRequest.definition:type_name -> piwork.core.services.v1.ServiceDefinition
	12, // 14: piwork.core.services.v1.ServiceLogs.error:type_name -> piwork.core.services.v1.SafeError
	0,  // 15: piwork.core.services.v1.WorkServices.ListRunModels:input_type -> piwork.core.services.v1.Empty
	1,  // 16: piwork.core.services.v1.WorkServices.ResolveRunModel:input_type -> piwork.core.services.v1.WorkPrivateRequest
	0,  // 17: piwork.core.services.v1.WorkServices.GetServiceInteractionBindings:input_type -> piwork.core.services.v1.Empty
	1,  // 18: piwork.core.services.v1.WorkServices.PrepareBrainCandidate:input_type -> piwork.core.services.v1.WorkPrivateRequest
	1,  // 19: piwork.core.services.v1.WorkServices.GetBrainCandidateState:input_type -> piwork.core.services.v1.WorkPrivateRequest
	1,  // 20: piwork.core.services.v1.WorkServices.AuthorizeHistoryMigration:input_type -> piwork.core.services.v1.WorkPrivateRequest
	0,  // 21: piwork.core.services.v1.WorkServices.GetDeploymentContext:input_type -> piwork.core.services.v1.Empty
	17, // 22: piwork.core.services.v1.WorkServices.CreateService:input_type -> piwork.core.services.v1.CreateServiceRequest
	0,  // 23: piwork.core.services.v1.WorkServices.ListServices:input_type -> piwork.core.services.v1.Empty
	19, // 24: piwork.core.services.v1.WorkServices.GetService:input_type -> piwork.core.services.v1.ServiceIdRequest
	21, // 25: piwork.core.services.v1.WorkServices.UpdateService:input_type -> piwork.core.services.v1.UpdateServiceRequest
	20, // 26: piwork.core.services.v1.WorkServices.StartService:input_type -> piwork.core.services.v1.MutateServiceRequest
	20, // 27: piwork.core.services.v1.WorkServices.StopService:input_type -> piwork.core.services.v1.MutateServiceRequest
	20, // 28: piwork.core.services.v1.WorkServices.RestartService:input_type -> piwork.core.services.v1.MutateServiceRequest
	20, // 29: piwork.core.services.v1.WorkServices.RemoveService:input_type -> piwork.core.services.v1.MutateServiceRequest
	20, // 30: piwork.core.services.v1.WorkServices.RetryService:input_type -> piwork.core.services.v1.MutateServiceRequest
	22, // 31: piwork.core.services.v1.WorkServices.GetOperation:input_type -> piwork.core.services.v1.OperationIdRequest
	23, // 32: piwork.core.services.v1.WorkServices.ReadServiceLogs:input_type -> piwork.core.services.v1.ReadServiceLogsRequest
	2,  // 33: piwork.core.services.v1.WorkServices.ListRunModels:output_type -> piwork.core.services.v1.WorkPrivateResponse
	3,  // 34: piwork.core.services.v1.WorkServices.ResolveRunModel:output_type -> piwork.core.services.v1.RunModelResolution
	2,  // 35: piwork.core.services.v1.WorkServices.GetServiceInteractionBindings:output_type -> piwork.core.services.v1.WorkPrivateResponse
	2,  // 36: piwork.core.services.v1.WorkServices.PrepareBrainCandidate:output_type -> piwork.core.services.v1.WorkPrivateResponse
	2,  // 37: piwork.core.services.v1.WorkServices.GetBrainCandidateState:output_type -> piwork.core.services.v1.WorkPrivateResponse
	2,  // 38: piwork.core.services.v1.WorkServices.AuthorizeHistoryMigration:output_type -> piwork.core.services.v1.WorkPrivateResponse
	16, // 39: piwork.core.services.v1.WorkServices.GetDeploymentContext:output_type -> piwork.core.services.v1.DeploymentContext
	15, // 40: piwork.core.services.v1.WorkServices.CreateService:output_type -> piwork.core.services.v1.Acceptance
	18, // 41: piwork.core.services.v1.WorkServices.ListServices:output_type -> piwork.core.services.v1.ListServicesResponse
	13, // 42: piwork.core.services.v1.WorkServices.GetService:output_type -> piwork.core.services.v1.ServiceView
	15, // 43: piwork.core.services.v1.WorkServices.UpdateService:output_type -> piwork.core.services.v1.Acceptance
	15, // 44: piwork.core.services.v1.WorkServices.StartService:output_type -> piwork.core.services.v1.Acceptance
	15, // 45: piwork.core.services.v1.WorkServices.StopService:output_type -> piwork.core.services.v1.Acceptance
	15, // 46: piwork.core.services.v1.WorkServices.RestartService:output_type -> piwork.core.services.v1.Acceptance
	15, // 47: piwork.core.services.v1.WorkServices.RemoveService:output_type -> piwork.core.services.v1.Acceptance
	15, // 48: piwork.core.services.v1.WorkServices.RetryService:output_type -> piwork.core.services.v1.Acceptance
	14, // 49: piwork.core.services.v1.WorkServices.GetOperation:output_type -> piwork.core.services.v1.OperationView
	24, // 50: piwork.core.services.v1.WorkServices.ReadServiceLogs:output_type -> piwork.core.services.v1.ServiceLogs
	33, // [33:51] is the sub-list for method output_type
	15, // [15:33] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_work_services_proto_init() }
func file_work_services_proto_init() {
	if File_work_services_proto != nil {
		return
	}
	file_work_services_proto_msgTypes[0].OneofWrappers = []any{}
	file_work_services_proto_msgTypes[8].OneofWrappers = []any{}
	file_work_services_proto_msgTypes[11].OneofWrappers = []any{}
	file_work_services_proto_msgTypes[13].OneofWrappers = []any{}
	file_work_services_proto_msgTypes[14].OneofWrappers = []any{}
	file_work_services_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_work_services_proto_rawDesc), len(file_work_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_work_services_proto_goTypes,
		DependencyIndexes: file_work_services_proto_depIdxs,
		MessageInfos:      file_work_services_proto_msgTypes,
	}.Build()
	File_work_services_proto = out.File
	file_work_services_proto_goTypes = nil
	file_work_services_proto_depIdxs = nil
}
