// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.2
// source: work-services.proto

package servicesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkServices_GetDeploymentContext_FullMethodName = "/piwork.core.services.v1.WorkServices/GetDeploymentContext"
	WorkServices_CreateService_FullMethodName        = "/piwork.core.services.v1.WorkServices/CreateService"
	WorkServices_ListServices_FullMethodName         = "/piwork.core.services.v1.WorkServices/ListServices"
	WorkServices_GetService_FullMethodName           = "/piwork.core.services.v1.WorkServices/GetService"
	WorkServices_UpdateService_FullMethodName        = "/piwork.core.services.v1.WorkServices/UpdateService"
	WorkServices_StartService_FullMethodName         = "/piwork.core.services.v1.WorkServices/StartService"
	WorkServices_StopService_FullMethodName          = "/piwork.core.services.v1.WorkServices/StopService"
	WorkServices_RestartService_FullMethodName       = "/piwork.core.services.v1.WorkServices/RestartService"
	WorkServices_RemoveService_FullMethodName        = "/piwork.core.services.v1.WorkServices/RemoveService"
	WorkServices_RetryService_FullMethodName         = "/piwork.core.services.v1.WorkServices/RetryService"
	WorkServices_GetOperation_FullMethodName         = "/piwork.core.services.v1.WorkServices/GetOperation"
	WorkServices_ReadServiceLogs_FullMethodName      = "/piwork.core.services.v1.WorkServices/ReadServiceLogs"
)

// WorkServicesClient is the client API for WorkServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkServicesClient interface {
	GetDeploymentContext(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeploymentContext, error)
	CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error)
	ListServices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListServicesResponse, error)
	GetService(ctx context.Context, in *ServiceIdRequest, opts ...grpc.CallOption) (*ServiceView, error)
	UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error)
	StartService(ctx context.Context, in *MutateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error)
	StopService(ctx context.Context, in *MutateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error)
	RestartService(ctx context.Context, in *MutateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error)
	RemoveService(ctx context.Context, in *MutateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error)
	RetryService(ctx context.Context, in *MutateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error)
	GetOperation(ctx context.Context, in *OperationIdRequest, opts ...grpc.CallOption) (*OperationView, error)
	ReadServiceLogs(ctx context.Context, in *ReadServiceLogsRequest, opts ...grpc.CallOption) (*ServiceLogs, error)
}

type workServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkServicesClient(cc grpc.ClientConnInterface) WorkServicesClient {
	return &workServicesClient{cc}
}

func (c *workServicesClient) GetDeploymentContext(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeploymentContext, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentContext)
	err := c.cc.Invoke(ctx, WorkServices_GetDeploymentContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workServicesClient) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acceptance)
	err := c.cc.Invoke(ctx, WorkServices_CreateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workServicesClient) ListServices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, WorkServices_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workServicesClient) GetService(ctx context.Context, in *ServiceIdRequest, opts ...grpc.CallOption) (*ServiceView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceView)
	err := c.cc.Invoke(ctx, WorkServices_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workServicesClient) UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acceptance)
	err := c.cc.Invoke(ctx, WorkServices_UpdateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workServicesClient) StartService(ctx context.Context, in *MutateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acceptance)
	err := c.cc.Invoke(ctx, WorkServices_StartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workServicesClient) StopService(ctx context.Context, in *MutateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acceptance)
	err := c.cc.Invoke(ctx, WorkServices_StopService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workServicesClient) RestartService(ctx context.Context, in *MutateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acceptance)
	err := c.cc.Invoke(ctx, WorkServices_RestartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workServicesClient) RemoveService(ctx context.Context, in *MutateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acceptance)
	err := c.cc.Invoke(ctx, WorkServices_RemoveService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workServicesClient) RetryService(ctx context.Context, in *MutateServiceRequest, opts ...grpc.CallOption) (*Acceptance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acceptance)
	err := c.cc.Invoke(ctx, WorkServices_RetryService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workServicesClient) GetOperation(ctx context.Context, in *OperationIdRequest, opts ...grpc.CallOption) (*OperationView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationView)
	err := c.cc.Invoke(ctx, WorkServices_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workServicesClient) ReadServiceLogs(ctx context.Context, in *ReadServiceLogsRequest, opts ...grpc.CallOption) (*ServiceLogs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceLogs)
	err := c.cc.Invoke(ctx, WorkServices_ReadServiceLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkServicesServer is the server API for WorkServices service.
// All implementations must embed UnimplementedWorkServicesServer
// for forward compatibility.
type WorkServicesServer interface {
	GetDeploymentContext(context.Context, *Empty) (*DeploymentContext, error)
	CreateService(context.Context, *CreateServiceRequest) (*Acceptance, error)
	ListServices(context.Context, *Empty) (*ListServicesResponse, error)
	GetService(context.Context, *ServiceIdRequest) (*ServiceView, error)
	UpdateService(context.Context, *UpdateServiceRequest) (*Acceptance, error)
	StartService(context.Context, *MutateServiceRequest) (*Acceptance, error)
	StopService(context.Context, *MutateServiceRequest) (*Acceptance, error)
	RestartService(context.Context, *MutateServiceRequest) (*Acceptance, error)
	RemoveService(context.Context, *MutateServiceRequest) (*Acceptance, error)
	RetryService(context.Context, *MutateServiceRequest) (*Acceptance, error)
	GetOperation(context.Context, *OperationIdRequest) (*OperationView, error)
	ReadServiceLogs(context.Context, *ReadServiceLogsRequest) (*ServiceLogs, error)
	mustEmbedUnimplementedWorkServicesServer()
}

// UnimplementedWorkServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkServicesServer struct{}

func (UnimplementedWorkServicesServer) GetDeploymentContext(context.Context, *Empty) (*DeploymentContext, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentContext not implemented")
}
func (UnimplementedWorkServicesServer) CreateService(context.Context, *CreateServiceRequest) (*Acceptance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedWorkServicesServer) ListServices(context.Context, *Empty) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedWorkServicesServer) GetService(context.Context, *ServiceIdRequest) (*ServiceView, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedWorkServicesServer) UpdateService(context.Context, *UpdateServiceRequest) (*Acceptance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedWorkServicesServer) StartService(context.Context, *MutateServiceRequest) (*Acceptance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartService not implemented")
}
func (UnimplementedWorkServicesServer) StopService(context.Context, *MutateServiceRequest) (*Acceptance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopService not implemented")
}
func (UnimplementedWorkServicesServer) RestartService(context.Context, *MutateServiceRequest) (*Acceptance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartService not implemented")
}
func (UnimplementedWorkServicesServer) RemoveService(context.Context, *MutateServiceRequest) (*Acceptance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveService not implemented")
}
func (UnimplementedWorkServicesServer) RetryService(context.Context, *MutateServiceRequest) (*Acceptance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryService not implemented")
}
func (UnimplementedWorkServicesServer) GetOperation(context.Context, *OperationIdRequest) (*OperationView, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedWorkServicesServer) ReadServiceLogs(context.Context, *ReadServiceLogsRequest) (*ServiceLogs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadServiceLogs not implemented")
}
func (UnimplementedWorkServicesServer) mustEmbedUnimplementedWorkServicesServer() {}
func (UnimplementedWorkServicesServer) testEmbeddedByValue()                      {}

// UnsafeWorkServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkServicesServer will
// result in compilation errors.
type UnsafeWorkServicesServer interface {
	mustEmbedUnimplementedWorkServicesServer()
}

func RegisterWorkServicesServer(s grpc.ServiceRegistrar, srv WorkServicesServer) {
	// If the following call pancis, it indicates UnimplementedWorkServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkServices_ServiceDesc, srv)
}

func _WorkServices_GetDeploymentContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServicesServer).GetDeploymentContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkServices_GetDeploymentContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServicesServer).GetDeploymentContext(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkServices_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServicesServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkServices_CreateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServicesServer).CreateService(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkServices_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServicesServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkServices_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServicesServer).ListServices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkServices_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServicesServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkServices_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServicesServer).GetService(ctx, req.(*ServiceIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkServices_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServicesServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkServices_UpdateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServicesServer).UpdateService(ctx, req.(*UpdateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkServices_StartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServicesServer).StartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkServices_StartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServicesServer).StartService(ctx, req.(*MutateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkServices_StopService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServicesServer).StopService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkServices_StopService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServicesServer).StopService(ctx, req.(*MutateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkServices_RestartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServicesServer).RestartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkServices_RestartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServicesServer).RestartService(ctx, req.(*MutateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkServices_RemoveService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServicesServer).RemoveService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkServices_RemoveService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServicesServer).RemoveService(ctx, req.(*MutateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkServices_RetryService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServicesServer).RetryService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkServices_RetryService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServicesServer).RetryService(ctx, req.(*MutateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkServices_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServicesServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkServices_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServicesServer).GetOperation(ctx, req.(*OperationIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkServices_ReadServiceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadServiceLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServicesServer).ReadServiceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkServices_ReadServiceLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServicesServer).ReadServiceLogs(ctx, req.(*ReadServiceLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkServices_ServiceDesc is the grpc.ServiceDesc for WorkServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "piwork.core.services.v1.WorkServices",
	HandlerType: (*WorkServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeploymentContext",
			Handler:    _WorkServices_GetDeploymentContext_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _WorkServices_CreateService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _WorkServices_ListServices_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _WorkServices_GetService_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _WorkServices_UpdateService_Handler,
		},
		{
			MethodName: "StartService",
			Handler:    _WorkServices_StartService_Handler,
		},
		{
			MethodName: "StopService",
			Handler:    _WorkServices_StopService_Handler,
		},
		{
			MethodName: "RestartService",
			Handler:    _WorkServices_RestartService_Handler,
		},
		{
			MethodName: "RemoveService",
			Handler:    _WorkServices_RemoveService_Handler,
		},
		{
			MethodName: "RetryService",
			Handler:    _WorkServices_RetryService_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _WorkServices_GetOperation_Handler,
		},
		{
			MethodName: "ReadServiceLogs",
			Handler:    _WorkServices_ReadServiceLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "work-services.proto",
}
