// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.36.2
// source: agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunState int32

const (
	RunState_RUN_STATE_UNSPECIFIED RunState = 0
	RunState_RUN_STATE_ACCEPTED    RunState = 1
	RunState_RUN_STATE_RUNNING     RunState = 2
	RunState_RUN_STATE_CANCELLING  RunState = 3
	RunState_RUN_STATE_SUCCEEDED   RunState = 4
	RunState_RUN_STATE_FAILED      RunState = 5
	RunState_RUN_STATE_CANCELLED   RunState = 6
	RunState_RUN_STATE_INTERRUPTED RunState = 7
)

// Enum value maps for RunState.
var (
	RunState_name = map[int32]string{
		0: "RUN_STATE_UNSPECIFIED",
		1: "RUN_STATE_ACCEPTED",
		2: "RUN_STATE_RUNNING",
		3: "RUN_STATE_CANCELLING",
		4: "RUN_STATE_SUCCEEDED",
		5: "RUN_STATE_FAILED",
		6: "RUN_STATE_CANCELLED",
		7: "RUN_STATE_INTERRUPTED",
	}
	RunState_value = map[string]int32{
		"RUN_STATE_UNSPECIFIED": 0,
		"RUN_STATE_ACCEPTED":    1,
		"RUN_STATE_RUNNING":     2,
		"RUN_STATE_CANCELLING":  3,
		"RUN_STATE_SUCCEEDED":   4,
		"RUN_STATE_FAILED":      5,
		"RUN_STATE_CANCELLED":   6,
		"RUN_STATE_INTERRUPTED": 7,
	}
)

func (x RunState) Enum() *RunState {
	p := new(RunState)
	*p = x
	return p
}

func (x RunState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (RunState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x RunState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunState.Descriptor instead.
func (RunState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type ReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessRequest) Reset() {
	*x = ReadinessRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessRequest) ProtoMessage() {}

func (x *ReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessRequest.ProtoReflect.Descriptor instead.
func (*ReadinessRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ReadinessRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *ReadinessRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ReadinessRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type ReadinessResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	WorkId                 string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Generation             uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	InstanceId             string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ProtocolVersion        string                 `protobuf:"bytes,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AcceptingRuns          bool                   `protobuf:"varint,5,opt,name=accepting_runs,json=acceptingRuns,proto3" json:"accepting_runs,omitempty"`
	Draining               bool                   `protobuf:"varint,6,opt,name=draining,proto3" json:"draining,omitempty"`
	ContextContractVersion uint32                 `protobuf:"varint,7,opt,name=context_contract_version,json=contextContractVersion,proto3" json:"context_contract_version,omitempty"`
	ContextIdentity        string                 `protobuf:"bytes,8,opt,name=context_identity,json=contextIdentity,proto3" json:"context_identity,omitempty"`
	InitializationComplete bool                   `protobuf:"varint,9,opt,name=initialization_complete,json=initializationComplete,proto3" json:"initialization_complete,omitempty"`
	LoadedSkills           []*LoadedSkill         `protobuf:"bytes,10,rep,name=loaded_skills,json=loadedSkills,proto3" json:"loaded_skills,omitempty"`
	ResolvedTools          []string               `protobuf:"bytes,11,rep,name=resolved_tools,json=resolvedTools,proto3" json:"resolved_tools,omitempty"`
	ActiveRunCount         uint32                 `protobuf:"varint,12,opt,name=active_run_count,json=activeRunCount,proto3" json:"active_run_count,omitempty"`
	PackageContractVersion uint32                 `protobuf:"varint,13,opt,name=package_contract_version,json=packageContractVersion,proto3" json:"package_contract_version,omitempty"`
	LoadedPackages         []*LoadedPackage       `protobuf:"bytes,14,rep,name=loaded_packages,json=loadedPackages,proto3" json:"loaded_packages,omitempty"`
	PackageResources       []*PackageResource     `protobuf:"bytes,15,rep,name=package_resources,json=packageResources,proto3" json:"package_resources,omitempty"`
	PackageDiagnostics     []*PackageDiagnostic   `protobuf:"bytes,16,rep,name=package_diagnostics,json=packageDiagnostics,proto3" json:"package_diagnostics,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReadinessResponse) Reset() {
	*x = ReadinessResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessResponse) ProtoMessage() {}

func (x *ReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessResponse.ProtoReflect.Descriptor instead.
func (*ReadinessResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ReadinessResponse) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *ReadinessResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ReadinessResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ReadinessResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ReadinessResponse) GetAcceptingRuns() bool {
	if x != nil {
		return x.AcceptingRuns
	}
	return false
}

func (x *ReadinessResponse) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

func (x *ReadinessResponse) GetContextContractVersion() uint32 {
	if x != nil {
		return x.ContextContractVersion
	}
	return 0
}

func (x *ReadinessResponse) GetContextIdentity() string {
	if x != nil {
		return x.ContextIdentity
	}
	return ""
}

func (x *ReadinessResponse) GetInitializationComplete() bool {
	if x != nil {
		return x.InitializationComplete
	}
	return false
}

func (x *ReadinessResponse) GetLoadedSkills() []*LoadedSkill {
	if x != nil {
		return x.LoadedSkills
	}
	return nil
}

func (x *ReadinessResponse) GetResolvedTools() []string {
	if x != nil {
		return x.ResolvedTools
	}
	return nil
}

func (x *ReadinessResponse) GetActiveRunCount() uint32 {
	if x != nil {
		return x.ActiveRunCount
	}
	return 0
}

func (x *ReadinessResponse) GetPackageContractVersion() uint32 {
	if x != nil {
		return x.PackageContractVersion
	}
	return 0
}

func (x *ReadinessResponse) GetLoadedPackages() []*LoadedPackage {
	if x != nil {
		return x.LoadedPackages
	}
	return nil
}

func (x *ReadinessResponse) GetPackageResources() []*PackageResource {
	if x != nil {
		return x.PackageResources
	}
	return nil
}

func (x *ReadinessResponse) GetPackageDiagnostics() []*PackageDiagnostic {
	if x != nil {
		return x.PackageDiagnostics
	}
	return nil
}

type LoadedPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContentDigest string                 `protobuf:"bytes,2,opt,name=content_digest,json=contentDigest,proto3" json:"content_digest,omitempty"`
	Extensions    uint32                 `protobuf:"varint,3,opt,name=extensions,proto3" json:"extensions,omitempty"`
	Skills        uint32                 `protobuf:"varint,4,opt,name=skills,proto3" json:"skills,omitempty"`
	Prompts       uint32                 `protobuf:"varint,5,opt,name=prompts,proto3" json:"prompts,omitempty"`
	Themes        uint32                 `protobuf:"varint,6,opt,name=themes,proto3" json:"themes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadedPackage) Reset() {
	*x = LoadedPackage{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadedPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadedPackage) ProtoMessage() {}

func (x *LoadedPackage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadedPackage.ProtoReflect.Descriptor instead.
func (*LoadedPackage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *LoadedPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadedPackage) GetContentDigest() string {
	if x != nil {
		return x.ContentDigest
	}
	return ""
}

func (x *LoadedPackage) GetExtensions() uint32 {
	if x != nil {
		return x.Extensions
	}
	return 0
}

func (x *LoadedPackage) GetSkills() uint32 {
	if x != nil {
		return x.Skills
	}
	return 0
}

func (x *LoadedPackage) GetPrompts() uint32 {
	if x != nil {
		return x.Prompts
	}
	return 0
}

func (x *LoadedPackage) GetThemes() uint32 {
	if x != nil {
		return x.Themes
	}
	return 0
}

type PackageResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageName   string                 `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageResource) Reset() {
	*x = PackageResource{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageResource) ProtoMessage() {}

func (x *PackageResource) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageResource.ProtoReflect.Descriptor instead.
func (*PackageResource) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *PackageResource) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *PackageResource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PackageResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PackageDiagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageName   string                 `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageDiagnostic) Reset() {
	*x = PackageDiagnostic{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageDiagnostic) ProtoMessage() {}

func (x *PackageDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageDiagnostic.ProtoReflect.Descriptor instead.
func (*PackageDiagnostic) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PackageDiagnostic) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *PackageDiagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PackageDiagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoadedSkill struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Identity         string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Loaded           bool                   `protobuf:"varint,3,opt,name=loaded,proto3" json:"loaded,omitempty"`
	ModelVisible     bool                   `protobuf:"varint,4,opt,name=model_visible,json=modelVisible,proto3" json:"model_visible,omitempty"`
	VisibilityReason string                 `protobuf:"bytes,5,opt,name=visibility_reason,json=visibilityReason,proto3" json:"visibility_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoadedSkill) Reset() {
	*x = LoadedSkill{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadedSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadedSkill) ProtoMessage() {}

func (x *LoadedSkill) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadedSkill.ProtoReflect.Descriptor instead.
func (*LoadedSkill) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *LoadedSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadedSkill) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *LoadedSkill) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *LoadedSkill) GetModelVisible() bool {
	if x != nil {
		return x.ModelVisible
	}
	return false
}

func (x *LoadedSkill) GetVisibilityReason() string {
	if x != nil {
		return x.VisibilityReason
	}
	return ""
}

type PrepareConfigurationChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareConfigurationChangeRequest) Reset() {
	*x = PrepareConfigurationChangeRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareConfigurationChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareConfigurationChangeRequest) ProtoMessage() {}

func (x *PrepareConfigurationChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareConfigurationChangeRequest.ProtoReflect.Descriptor instead.
func (*PrepareConfigurationChangeRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *PrepareConfigurationChangeRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *PrepareConfigurationChangeRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *PrepareConfigurationChangeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type PrepareConfigurationChangeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Prepared       bool                   `protobuf:"varint,1,opt,name=prepared,proto3" json:"prepared,omitempty"`
	Busy           bool                   `protobuf:"varint,2,opt,name=busy,proto3" json:"busy,omitempty"`
	ActiveRunCount uint32                 `protobuf:"varint,3,opt,name=active_run_count,json=activeRunCount,proto3" json:"active_run_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrepareConfigurationChangeResponse) Reset() {
	*x = PrepareConfigurationChangeResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareConfigurationChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareConfigurationChangeResponse) ProtoMessage() {}

func (x *PrepareConfigurationChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareConfigurationChangeResponse.ProtoReflect.Descriptor instead.
func (*PrepareConfigurationChangeResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *PrepareConfigurationChangeResponse) GetPrepared() bool {
	if x != nil {
		return x.Prepared
	}
	return false
}

func (x *PrepareConfigurationChangeResponse) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

func (x *PrepareConfigurationChangeResponse) GetActiveRunCount() uint32 {
	if x != nil {
		return x.ActiveRunCount
	}
	return 0
}

type DrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DrainRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *DrainRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *DrainRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DrainRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type DrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drained       bool                   `protobuf:"varint,1,opt,name=drained,proto3" json:"drained,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DrainResponse) GetDrained() bool {
	if x != nil {
		return x.Drained
	}
	return false
}

type Session struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkId         string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SdkHistoryPath string                 `protobuf:"bytes,3,opt,name=sdk_history_path,json=sdkHistoryPath,proto3" json:"sdk_history_path,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Session) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetSdkHistoryPath() string {
	if x != nil {
		return x.SdkHistoryPath
	}
	return ""
}

func (x *Session) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Session) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkId         string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSessionRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *CreateSessionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ListSessionsRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *ListSessionsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSessionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ReadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSessionRequest) Reset() {
	*x = ReadSessionRequest{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSessionRequest) ProtoMessage() {}

func (x *ReadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSessionRequest.ProtoReflect.Descriptor instead.
func (*ReadSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ReadSessionRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *ReadSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Messages      []*SessionMessage      `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionHistory) Reset() {
	*x = SessionHistory{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionHistory) ProtoMessage() {}

func (x *SessionHistory) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionHistory.ProtoReflect.Descriptor instead.
func (*SessionHistory) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *SessionHistory) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *SessionHistory) GetMessages() []*SessionMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SessionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage) Reset() {
	*x = SessionMessage{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage) ProtoMessage() {}

func (x *SessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage.ProtoReflect.Descriptor instead.
func (*SessionMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *SessionMessage) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *SessionMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SessionMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SessionMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RunError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunError) Reset() {
	*x = RunError{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunError) ProtoMessage() {}

func (x *RunError) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunError.ProtoReflect.Descriptor instead.
func (*RunError) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *RunError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RunError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RunError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type Run struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	WorkId                    string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	SessionId                 string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId                     string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SubmissionKey             string                 `protobuf:"bytes,4,opt,name=submission_key,json=submissionKey,proto3" json:"submission_key,omitempty"`
	State                     RunState               `protobuf:"varint,5,opt,name=state,proto3,enum=piwork.agent.v1.RunState" json:"state,omitempty"`
	PromptDigest              string                 `protobuf:"bytes,6,opt,name=prompt_digest,json=promptDigest,proto3" json:"prompt_digest,omitempty"`
	FinalText                 string                 `protobuf:"bytes,7,opt,name=final_text,json=finalText,proto3" json:"final_text,omitempty"`
	Error                     *RunError              `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	AcceptedAt                string                 `protobuf:"bytes,9,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	StartedAt                 string                 `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt                string                 `protobuf:"bytes,11,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	EarliestAvailableSequence uint64                 `protobuf:"varint,12,opt,name=earliest_available_sequence,json=earliestAvailableSequence,proto3" json:"earliest_available_sequence,omitempty"`
	LatestSequence            uint64                 `protobuf:"varint,13,opt,name=latest_sequence,json=latestSequence,proto3" json:"latest_sequence,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *Run) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *Run) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Run) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Run) GetSubmissionKey() string {
	if x != nil {
		return x.SubmissionKey
	}
	return ""
}

func (x *Run) GetState() RunState {
	if x != nil {
		return x.State
	}
	return RunState_RUN_STATE_UNSPECIFIED
}

func (x *Run) GetPromptDigest() string {
	if x != nil {
		return x.PromptDigest
	}
	return ""
}

func (x *Run) GetFinalText() string {
	if x != nil {
		return x.FinalText
	}
	return ""
}

func (x *Run) GetError() *RunError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Run) GetAcceptedAt() string {
	if x != nil {
		return x.AcceptedAt
	}
	return ""
}

func (x *Run) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Run) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *Run) GetEarliestAvailableSequence() uint64 {
	if x != nil {
		return x.EarliestAvailableSequence
	}
	return 0
}

func (x *Run) GetLatestSequence() uint64 {
	if x != nil {
		return x.LatestSequence
	}
	return 0
}

type SubmitRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SubmissionKey string                 `protobuf:"bytes,3,opt,name=submission_key,json=submissionKey,proto3" json:"submission_key,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRunRequest) Reset() {
	*x = SubmitRunRequest{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRunRequest) ProtoMessage() {}

func (x *SubmitRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRunRequest.ProtoReflect.Descriptor instead.
func (*SubmitRunRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *SubmitRunRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *SubmitRunRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitRunRequest) GetSubmissionKey() string {
	if x != nil {
		return x.SubmissionKey
	}
	return ""
}

func (x *SubmitRunRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type SubmitRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *Run                   `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	Reused        bool                   `protobuf:"varint,2,opt,name=reused,proto3" json:"reused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRunResponse) Reset() {
	*x = SubmitRunResponse{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRunResponse) ProtoMessage() {}

func (x *SubmitRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRunResponse.ProtoReflect.Descriptor instead.
func (*SubmitRunResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *SubmitRunResponse) GetRun() *Run {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *SubmitRunResponse) GetReused() bool {
	if x != nil {
		return x.Reused
	}
	return false
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *GetRunRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *GetRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type WatchRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AfterSequence *uint64                `protobuf:"varint,3,opt,name=after_sequence,json=afterSequence,proto3,oneof" json:"after_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRunRequest) Reset() {
	*x = WatchRunRequest{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRunRequest) ProtoMessage() {}

func (x *WatchRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRunRequest.ProtoReflect.Descriptor instead.
func (*WatchRunRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *WatchRunRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *WatchRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WatchRunRequest) GetAfterSequence() uint64 {
	if x != nil && x.AfterSequence != nil {
		return *x.AfterSequence
	}
	return 0
}

type CancelRunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkId         string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	RunId          string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *CancelRunRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CancelRunRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type TextEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextEvent) Reset() {
	*x = TextEvent{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEvent) ProtoMessage() {}

func (x *TextEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEvent.ProtoReflect.Descriptor instead.
func (*TextEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

func (x *TextEvent) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

type ToolEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,3,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Phase         string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	IsError       bool                   `protobuf:"varint,5,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent) Reset() {
	*x = ToolEvent{}
	mi := &file_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent) ProtoMessage() {}

func (x *ToolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent.ProtoReflect.Descriptor instead.
func (*ToolEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *ToolEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ToolEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolEvent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ToolEvent) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type StateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         RunState               `protobuf:"varint,1,opt,name=state,proto3,enum=piwork.agent.v1.RunState" json:"state,omitempty"`
	FinalText     string                 `protobuf:"bytes,2,opt,name=final_text,json=finalText,proto3" json:"final_text,omitempty"`
	Error         *RunError              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateEvent) Reset() {
	*x = StateEvent{}
	mi := &file_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateEvent) ProtoMessage() {}

func (x *StateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateEvent.ProtoReflect.Descriptor instead.
func (*StateEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{26}
}

func (x *StateEvent) GetState() RunState {
	if x != nil {
		return x.State
	}
	return RunState_RUN_STATE_UNSPECIFIED
}

func (x *StateEvent) GetFinalText() string {
	if x != nil {
		return x.FinalText
	}
	return ""
}

func (x *StateEvent) GetError() *RunError {
	if x != nil {
		return x.Error
	}
	return nil
}

type RunEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	WorkId    string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId     string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Sequence  uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	CreatedAt string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RunEvent_Text
	//	*RunEvent_Tool
	//	*RunEvent_State
	Kind          isRunEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{27}
}

func (x *RunEvent) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *RunEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RunEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RunEvent) GetKind() isRunEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RunEvent) GetText() *TextEvent {
	if x != nil {
		if x, ok := x.Kind.(*RunEvent_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *RunEvent) GetTool() *ToolEvent {
	if x != nil {
		if x, ok := x.Kind.(*RunEvent_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *RunEvent) GetState() *StateEvent {
	if x != nil {
		if x, ok := x.Kind.(*RunEvent_State); ok {
			return x.State
		}
	}
	return nil
}

type isRunEvent_Kind interface {
	isRunEvent_Kind()
}

type RunEvent_Text struct {
	Text *TextEvent `protobuf:"bytes,6,opt,name=text,proto3,oneof"`
}

type RunEvent_Tool struct {
	Tool *ToolEvent `protobuf:"bytes,7,opt,name=tool,proto3,oneof"`
}

type RunEvent_State struct {
	State *StateEvent `protobuf:"bytes,8,opt,name=state,proto3,oneof"`
}

func (*RunEvent_Text) isRunEvent_Kind() {}

func (*RunEvent_Tool) isRunEvent_Kind() {}

func (*RunEvent_State) isRunEvent_Kind() {}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x0fpiwork.agent.v1\"l\n" +
	"\x10ReadinessRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\"\xb4\x06\n" +
	"\x11ReadinessResponse\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eaccepting_runs\x18\x05 \x01(\bR\racceptingRuns\x12\x1a\n" +
	"\bdraining\x18\x06 \x01(\bR\bdraining\x128\n" +
	"\x18context_contract_version\x18\a \x01(\rR\x16contextContractVersion\x12)\n" +
	"\x10context_identity\x18\b \x01(\tR\x0fcontextIdentity\x127\n" +
	"\x17initialization_complete\x18\t \x01(\bR\x16initializationComplete\x12A\n" +
	"\rloaded_skills\x18\n" +
	" \x03(\v2\x1c.piwork.agent.v1.LoadedSkillR\floadedSkills\x12%\n" +
	"\x0eresolved_tools\x18\v \x03(\tR\rresolvedTools\x12(\n" +
	"\x10active_run_count\x18\f \x01(\rR\x0eactiveRunCount\x128\n" +
	"\x18package_contract_version\x18\r \x01(\rR\x16packageContractVersion\x12G\n" +
	"\x0floaded_packages\x18\x0e \x03(\v2\x1e.piwork.agent.v1.LoadedPackageR\x0eloadedPackages\x12M\n" +
	"\x11package_resources\x18\x0f \x03(\v2 .piwork.agent.v1.PackageResourceR\x10packageResources\x12S\n" +
	"\x13package_diagnostics\x18\x10 \x03(\v2\".piwork.agent.v1.PackageDiagnosticR\x12packageDiagnostics\"\xb4\x01\n" +
	"\rLoadedPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0econtent_digest\x18\x02 \x01(\tR\rcontentDigest\x12\x1e\n" +
	"\n" +
	"extensions\x18\x03 \x01(\rR\n" +
	"extensions\x12\x16\n" +
	"\x06skills\x18\x04 \x01(\rR\x06skills\x12\x18\n" +
	"\aprompts\x18\x05 \x01(\rR\aprompts\x12\x16\n" +
	"\x06themes\x18\x06 \x01(\rR\x06themes\"\\\n" +
	"\x0fPackageResource\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"d\n" +
	"\x11PackageDiagnostic\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa7\x01\n" +
	"\vLoadedSkill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x16\n" +
	"\x06loaded\x18\x03 \x01(\bR\x06loaded\x12#\n" +
	"\rmodel_visible\x18\x04 \x01(\bR\fmodelVisible\x12+\n" +
	"\x11visibility_reason\x18\x05 \x01(\tR\x10visibilityReason\"}\n" +
	"!PrepareConfigurationChangeRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\"~\n" +
	"\"PrepareConfigurationChangeResponse\x12\x1a\n" +
	"\bprepared\x18\x01 \x01(\bR\bprepared\x12\x12\n" +
	"\x04busy\x18\x02 \x01(\bR\x04busy\x12(\n" +
	"\x10active_run_count\x18\x03 \x01(\rR\x0eactiveRunCount\"\x87\x01\n" +
	"\fDrainRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\rR\ttimeoutMs\")\n" +
	"\rDrainResponse\x12\x18\n" +
	"\adrained\x18\x01 \x01(\bR\adrained\"\xa9\x01\n" +
	"\aSession\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12(\n" +
	"\x10sdk_history_path\x18\x03 \x01(\tR\x0esdkHistoryPath\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"X\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"j\n" +
	"\x13ListSessionsRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"t\n" +
	"\x14ListSessionsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.piwork.agent.v1.SessionR\bsessions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"L\n" +
	"\x12ReadSessionRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x81\x01\n" +
	"\x0eSessionHistory\x122\n" +
	"\asession\x18\x01 \x01(\v2\x18.piwork.agent.v1.SessionR\asession\x12;\n" +
	"\bmessages\x18\x02 \x03(\v2\x1f.piwork.agent.v1.SessionMessageR\bmessages\"r\n" +
	"\x0eSessionMessage\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"V\n" +
	"\bRunError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\xeb\x03\n" +
	"\x03Run\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12%\n" +
	"\x0esubmission_key\x18\x04 \x01(\tR\rsubmissionKey\x12/\n" +
	"\x05state\x18\x05 \x01(\x0e2\x19.piwork.agent.v1.RunStateR\x05state\x12#\n" +
	"\rprompt_digest\x18\x06 \x01(\tR\fpromptDigest\x12\x1d\n" +
	"\n" +
	"final_text\x18\a \x01(\tR\tfinalText\x12/\n" +
	"\x05error\x18\b \x01(\v2\x19.piwork.agent.v1.RunErrorR\x05error\x12\x1f\n" +
	"\vaccepted_at\x18\t \x01(\tR\n" +
	"acceptedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\v \x01(\tR\n" +
	"finishedAt\x12>\n" +
	"\x1bearliest_available_sequence\x18\f \x01(\x04R\x19earliestAvailableSequence\x12'\n" +
	"\x0flatest_sequence\x18\r \x01(\x04R\x0elatestSequence\"\x89\x01\n" +
	"\x10SubmitRunRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12%\n" +
	"\x0esubmission_key\x18\x03 \x01(\tR\rsubmissionKey\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\"S\n" +
	"\x11SubmitRunResponse\x12&\n" +
	"\x03run\x18\x01 \x01(\v2\x14.piwork.agent.v1.RunR\x03run\x12\x16\n" +
	"\x06reused\x18\x02 \x01(\bR\x06reused\"?\n" +
	"\rGetRunRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"\x80\x01\n" +
	"\x0fWatchRunRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12*\n" +
	"\x0eafter_sequence\x18\x03 \x01(\x04H\x00R\rafterSequence\x88\x01\x01B\x11\n" +
	"\x0f_after_sequence\"k\n" +
	"\x10CancelRunRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"!\n" +
	"\tTextEvent\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\"\x98\x01\n" +
	"\tToolEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12 \n" +
	"\ftool_call_id\x18\x03 \x01(\tR\n" +
	"toolCallId\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x19\n" +
	"\bis_error\x18\x05 \x01(\bR\aisError\"\x8d\x01\n" +
	"\n" +
	"StateEvent\x12/\n" +
	"\x05state\x18\x01 \x01(\x0e2\x19.piwork.agent.v1.RunStateR\x05state\x12\x1d\n" +
	"\n" +
	"final_text\x18\x02 \x01(\tR\tfinalText\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.piwork.agent.v1.RunErrorR\x05error\"\xb5\x02\n" +
	"\bRunEvent\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x120\n" +
	"\x04text\x18\x06 \x01(\v2\x1a.piwork.agent.v1.TextEventH\x00R\x04text\x120\n" +
	"\x04tool\x18\a \x01(\v2\x1a.piwork.agent.v1.ToolEventH\x00R\x04tool\x123\n" +
	"\x05state\x18\b \x01(\v2\x1b.piwork.agent.v1.StateEventH\x00R\x05stateB\x06\n" +
	"\x04kind*\xd1\x01\n" +
	"\bRunState\x12\x19\n" +
	"\x15RUN_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RUN_STATE_ACCEPTED\x10\x01\x12\x15\n" +
	"\x11RUN_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14RUN_STATE_CANCELLING\x10\x03\x12\x17\n" +
	"\x13RUN_STATE_SUCCEEDED\x10\x04\x12\x14\n" +
	"\x10RUN_STATE_FAILED\x10\x05\x12\x17\n" +
	"\x13RUN_STATE_CANCELLED\x10\x06\x12\x19\n" +
	"\x15RUN_STATE_INTERRUPTED\x10\a2\xdb\x06\n" +
	"\fAgentService\x12R\n" +
	"\tReadiness\x12!.piwork.agent.v1.ReadinessRequest\x1a\".piwork.agent.v1.ReadinessResponse\x12\x85\x01\n" +
	"\x1aPrepareConfigurationChange\x122.piwork.agent.v1.PrepareConfigurationChangeRequest\x1a3.piwork.agent.v1.PrepareConfigurationChangeResponse\x12F\n" +
	"\x05Drain\x12\x1d.piwork.agent.v1.DrainRequest\x1a\x1e.piwork.agent.v1.DrainResponse\x12P\n" +
	"\rCreateSession\x12%.piwork.agent.v1.CreateSessionRequest\x1a\x18.piwork.agent.v1.Session\x12[\n" +
	"\fListSessions\x12$.piwork.agent.v1.ListSessionsRequest\x1a%.piwork.agent.v1.ListSessionsResponse\x12S\n" +
	"\vReadSession\x12#.piwork.agent.v1.ReadSessionRequest\x1a\x1f.piwork.agent.v1.SessionHistory\x12R\n" +
	"\tSubmitRun\x12!.piwork.agent.v1.SubmitRunRequest\x1a\".piwork.agent.v1.SubmitRunResponse\x12>\n" +
	"\x06GetRun\x12\x1e.piwork.agent.v1.GetRunRequest\x1a\x14.piwork.agent.v1.Run\x12I\n" +
	"\bWatchRun\x12 .piwork.agent.v1.WatchRunRequest\x1a\x19.piwork.agent.v1.RunEvent0\x01\x12D\n" +
	"\tCancelRun\x12!.piwork.agent.v1.CancelRunRequest\x1a\x14.piwork.agent.v1.Runb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_agent_proto_goTypes = []any{
	(RunState)(0),                              // 0: piwork.agent.v1.RunState
	(*ReadinessRequest)(nil),                   // 1: piwork.agent.v1.ReadinessRequest
	(*ReadinessResponse)(nil),                  // 2: piwork.agent.v1.ReadinessResponse
	(*LoadedPackage)(nil),                      // 3: piwork.agent.v1.LoadedPackage
	(*PackageResource)(nil),                    // 4: piwork.agent.v1.PackageResource
	(*PackageDiagnostic)(nil),                  // 5: piwork.agent.v1.PackageDiagnostic
	(*LoadedSkill)(nil),                        // 6: piwork.agent.v1.LoadedSkill
	(*PrepareConfigurationChangeRequest)(nil),  // 7: piwork.agent.v1.PrepareConfigurationChangeRequest
	(*PrepareConfigurationChangeResponse)(nil), // 8: piwork.agent.v1.PrepareConfigurationChangeResponse
	(*DrainRequest)(nil),                       // 9: piwork.agent.v1.DrainRequest
	(*DrainResponse)(nil),                      // 10: piwork.agent.v1.DrainResponse
	(*Session)(nil),                            // 11: piwork.agent.v1.Session
	(*CreateSessionRequest)(nil),               // 12: piwork.agent.v1.CreateSessionRequest
	(*ListSessionsRequest)(nil),                // 13: piwork.agent.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),               // 14: piwork.agent.v1.ListSessionsResponse
	(*ReadSessionRequest)(nil),                 // 15: piwork.agent.v1.ReadSessionRequest
	(*SessionHistory)(nil),                     // 16: piwork.agent.v1.SessionHistory
	(*SessionMessage)(nil),                     // 17: piwork.agent.v1.SessionMessage
	(*RunError)(nil),                           // 18: piwork.agent.v1.RunError
	(*Run)(nil),                                // 19: piwork.agent.v1.Run
	(*SubmitRunRequest)(nil),                   // 20: piwork.agent.v1.SubmitRunRequest
	(*SubmitRunResponse)(nil),                  // 21: piwork.agent.v1.SubmitRunResponse
	(*GetRunRequest)(nil),                      // 22: piwork.agent.v1.GetRunRequest
	(*WatchRunRequest)(nil),                    // 23: piwork.agent.v1.WatchRunRequest
	(*CancelRunRequest)(nil),                   // 24: piwork.agent.v1.CancelRunRequest
	(*TextEvent)(nil),                          // 25: piwork.agent.v1.TextEvent
	(*ToolEvent)(nil),                          // 26: piwork.agent.v1.ToolEvent
	(*StateEvent)(nil),                         // 27: piwork.agent.v1.StateEvent
	(*RunEvent)(nil),                           // 28: piwork.agent.v1.RunEvent
}
var file_agent_proto_depIdxs = []int32{
	6,  // 0: piwork.agent.v1.ReadinessResponse.loaded_skills:type_name -> piwork.agent.v1.LoadedSkill
	3,  // 1: piwork.agent.v1.ReadinessResponse.loaded_packages:type_name -> piwork.agent.v1.LoadedPackage
	4,  // 2: piwork.agent.v1.ReadinessResponse.package_resources:type_name -> piwork.agent.v1.PackageResource
	5,  // 3: piwork.agent.v1.ReadinessResponse.package_diagnostics:type_name -> piwork.agent.v1.PackageDiagnostic
	11, // 4: piwork.agent.v1.ListSessionsResponse.sessions:type_name -> piwork.agent.v1.Session
	11, // 5: piwork.agent.v1.SessionHistory.session:type_name -> piwork.agent.v1.Session
	17, // 6: piwork.agent.v1.SessionHistory.messages:type_name -> piwork.agent.v1.SessionMessage
	0,  // 7: piwork.agent.v1.Run.state:type_name -> piwork.agent.v1.RunState
	18, // 8: piwork.agent.v1.Run.error:type_name -> piwork.agent.v1.RunError
	19, // 9: piwork.agent.v1.SubmitRunResponse.run:type_name -> piwork.agent.v1.Run
	0,  // 10: piwork.agent.v1.StateEvent.state:type_name -> piwork.agent.v1.RunState
	18, // 11: piwork.agent.v1.StateEvent.error:type_name -> piwork.agent.v1.RunError
	25, // 12: piwork.agent.v1.RunEvent.text:type_name -> piwork.agent.v1.TextEvent
	26, // 13: piwork.agent.v1.RunEvent.tool:type_name -> piwork.agent.v1.ToolEvent
	27, // 14: piwork.agent.v1.RunEvent.state:type_name -> piwork.agent.v1.StateEvent
	1,  // 15: piwork.agent.v1.AgentService.Readiness:input_type -> piwork.agent.v1.ReadinessRequest
	7,  // 16: piwork.agent.v1.AgentService.PrepareConfigurationChange:input_type -> piwork.agent.v1.PrepareConfigurationChangeRequest
	9,  // 17: piwork.agent.v1.AgentService.Drain:input_type -> piwork.agent.v1.DrainRequest
	12, // 18: piwork.agent.v1.AgentService.CreateSession:input_type -> piwork.agent.v1.CreateSessionRequest
	13, // 19: piwork.agent.v1.AgentService.ListSessions:input_type -> piwork.agent.v1.ListSessionsRequest
	15, // 20: piwork.agent.v1.AgentService.ReadSession:input_type -> piwork.agent.v1.ReadSessionRequest
	20, // 21: piwork.agent.v1.AgentService.SubmitRun:input_type -> piwork.agent.v1.SubmitRunRequest
	22, // 22: piwork.agent.v1.AgentService.GetRun:input_type -> piwork.agent.v1.GetRunRequest
	23, // 23: piwork.agent.v1.AgentService.WatchRun:input_type -> piwork.agent.v1.WatchRunRequest
	24, // 24: piwork.agent.v1.AgentService.CancelRun:input_type -> piwork.agent.v1.CancelRunRequest
	2,  // 25: piwork.agent.v1.AgentService.Readiness:output_type -> piwork.agent.v1.ReadinessResponse
	8,  // 26: piwork.agent.v1.AgentService.PrepareConfigurationChange:output_type -> piwork.agent.v1.PrepareConfigurationChangeResponse
	10, // 27: piwork.agent.v1.AgentService.Drain:output_type -> piwork.agent.v1.DrainResponse
	11, // 28: piwork.agent.v1.AgentService.CreateSession:output_type -> piwork.agent.v1.Session
	14, // 29: piwork.agent.v1.AgentService.ListSessions:output_type -> piwork.agent.v1.ListSessionsResponse
	16, // 30: piwork.agent.v1.AgentService.ReadSession:output_type -> piwork.agent.v1.SessionHistory
	21, // 31: piwork.agent.v1.AgentService.SubmitRun:output_type -> piwork.agent.v1.SubmitRunResponse
	19, // 32: piwork.agent.v1.AgentService.GetRun:output_type -> piwork.agent.v1.Run
	28, // 33: piwork.agent.v1.AgentService.WatchRun:output_type -> piwork.agent.v1.RunEvent
	19, // 34: piwork.agent.v1.AgentService.CancelRun:output_type -> piwork.agent.v1.Run
	25, // [25:35] is the sub-list for method output_type
	15, // [15:25] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[22].OneofWrappers = []any{}
	file_agent_proto_msgTypes[27].OneofWrappers = []any{
		(*RunEvent_Text)(nil),
		(*RunEvent_Tool)(nil),
		(*RunEvent_State)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
