// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.2
// source: agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_RefreshServiceInteractionBindings_FullMethodName = "/piwork.agent.v1.AgentService/RefreshServiceInteractionBindings"
	AgentService_Readiness_FullMethodName                         = "/piwork.agent.v1.AgentService/Readiness"
	AgentService_PrepareConfigurationChange_FullMethodName        = "/piwork.agent.v1.AgentService/PrepareConfigurationChange"
	AgentService_Drain_FullMethodName                             = "/piwork.agent.v1.AgentService/Drain"
	AgentService_CreateSession_FullMethodName                     = "/piwork.agent.v1.AgentService/CreateSession"
	AgentService_ListSessions_FullMethodName                      = "/piwork.agent.v1.AgentService/ListSessions"
	AgentService_ReadSession_FullMethodName                       = "/piwork.agent.v1.AgentService/ReadSession"
	AgentService_SubmitRun_FullMethodName                         = "/piwork.agent.v1.AgentService/SubmitRun"
	AgentService_GetRun_FullMethodName                            = "/piwork.agent.v1.AgentService/GetRun"
	AgentService_WatchRun_FullMethodName                          = "/piwork.agent.v1.AgentService/WatchRun"
	AgentService_CancelRun_FullMethodName                         = "/piwork.agent.v1.AgentService/CancelRun"
	AgentService_ListRunModels_FullMethodName                     = "/piwork.agent.v1.AgentService/ListRunModels"
	AgentService_SetSessionModel_FullMethodName                   = "/piwork.agent.v1.AgentService/SetSessionModel"
	AgentService_ListAgentRequests_FullMethodName                 = "/piwork.agent.v1.AgentService/ListAgentRequests"
	AgentService_GetAgentRequest_FullMethodName                   = "/piwork.agent.v1.AgentService/GetAgentRequest"
	AgentService_CancelAgentRequest_FullMethodName                = "/piwork.agent.v1.AgentService/CancelAgentRequest"
	AgentService_RetryAgentRequest_FullMethodName                 = "/piwork.agent.v1.AgentService/RetryAgentRequest"
	AgentService_GetAgentEvidence_FullMethodName                  = "/piwork.agent.v1.AgentService/GetAgentEvidence"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	RefreshServiceInteractionBindings(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error)
	Readiness(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error)
	PrepareConfigurationChange(ctx context.Context, in *PrepareConfigurationChangeRequest, opts ...grpc.CallOption) (*PrepareConfigurationChangeResponse, error)
	Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	ReadSession(ctx context.Context, in *ReadSessionRequest, opts ...grpc.CallOption) (*SessionHistory, error)
	SubmitRun(ctx context.Context, in *SubmitRunRequest, opts ...grpc.CallOption) (*SubmitRunResponse, error)
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*Run, error)
	WatchRun(ctx context.Context, in *WatchRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error)
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*Run, error)
	ListRunModels(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error)
	SetSessionModel(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*Session, error)
	ListAgentRequests(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error)
	GetAgentRequest(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error)
	CancelAgentRequest(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error)
	RetryAgentRequest(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error)
	GetAgentEvidence(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RefreshServiceInteractionBindings(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentContentResponse)
	err := c.cc.Invoke(ctx, AgentService_RefreshServiceInteractionBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Readiness(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadinessResponse)
	err := c.cc.Invoke(ctx, AgentService_Readiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PrepareConfigurationChange(ctx context.Context, in *PrepareConfigurationChangeRequest, opts ...grpc.CallOption) (*PrepareConfigurationChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareConfigurationChangeResponse)
	err := c.cc.Invoke(ctx, AgentService_PrepareConfigurationChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainResponse)
	err := c.cc.Invoke(ctx, AgentService_Drain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, AgentService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReadSession(ctx context.Context, in *ReadSessionRequest, opts ...grpc.CallOption) (*SessionHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionHistory)
	err := c.cc.Invoke(ctx, AgentService_ReadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SubmitRun(ctx context.Context, in *SubmitRunRequest, opts ...grpc.CallOption) (*SubmitRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRunResponse)
	err := c.cc.Invoke(ctx, AgentService_SubmitRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, AgentService_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) WatchRun(ctx context.Context, in *WatchRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_WatchRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRunRequest, RunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_WatchRunClient = grpc.ServerStreamingClient[RunEvent]

func (c *agentServiceClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, AgentService_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListRunModels(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentContentResponse)
	err := c.cc.Invoke(ctx, AgentService_ListRunModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SetSessionModel(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, AgentService_SetSessionModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListAgentRequests(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentContentResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgentRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgentRequest(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentContentResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAgentRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CancelAgentRequest(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentContentResponse)
	err := c.cc.Invoke(ctx, AgentService_CancelAgentRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RetryAgentRequest(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentContentResponse)
	err := c.cc.Invoke(ctx, AgentService_RetryAgentRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgentEvidence(ctx context.Context, in *AgentContentRequest, opts ...grpc.CallOption) (*AgentContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentContentResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAgentEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	RefreshServiceInteractionBindings(context.Context, *AgentContentRequest) (*AgentContentResponse, error)
	Readiness(context.Context, *ReadinessRequest) (*ReadinessResponse, error)
	PrepareConfigurationChange(context.Context, *PrepareConfigurationChangeRequest) (*PrepareConfigurationChangeResponse, error)
	Drain(context.Context, *DrainRequest) (*DrainResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	ReadSession(context.Context, *ReadSessionRequest) (*SessionHistory, error)
	SubmitRun(context.Context, *SubmitRunRequest) (*SubmitRunResponse, error)
	GetRun(context.Context, *GetRunRequest) (*Run, error)
	WatchRun(*WatchRunRequest, grpc.ServerStreamingServer[RunEvent]) error
	CancelRun(context.Context, *CancelRunRequest) (*Run, error)
	ListRunModels(context.Context, *AgentContentRequest) (*AgentContentResponse, error)
	SetSessionModel(context.Context, *AgentContentRequest) (*Session, error)
	ListAgentRequests(context.Context, *AgentContentRequest) (*AgentContentResponse, error)
	GetAgentRequest(context.Context, *AgentContentRequest) (*AgentContentResponse, error)
	CancelAgentRequest(context.Context, *AgentContentRequest) (*AgentContentResponse, error)
	RetryAgentRequest(context.Context, *AgentContentRequest) (*AgentContentResponse, error)
	GetAgentEvidence(context.Context, *AgentContentRequest) (*AgentContentResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RefreshServiceInteractionBindings(context.Context, *AgentContentRequest) (*AgentContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshServiceInteractionBindings not implemented")
}
func (UnimplementedAgentServiceServer) Readiness(context.Context, *ReadinessRequest) (*ReadinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Readiness not implemented")
}
func (UnimplementedAgentServiceServer) PrepareConfigurationChange(context.Context, *PrepareConfigurationChangeRequest) (*PrepareConfigurationChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareConfigurationChange not implemented")
}
func (UnimplementedAgentServiceServer) Drain(context.Context, *DrainRequest) (*DrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Drain not implemented")
}
func (UnimplementedAgentServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedAgentServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedAgentServiceServer) ReadSession(context.Context, *ReadSessionRequest) (*SessionHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadSession not implemented")
}
func (UnimplementedAgentServiceServer) SubmitRun(context.Context, *SubmitRunRequest) (*SubmitRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRun not implemented")
}
func (UnimplementedAgentServiceServer) GetRun(context.Context, *GetRunRequest) (*Run, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedAgentServiceServer) WatchRun(*WatchRunRequest, grpc.ServerStreamingServer[RunEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchRun not implemented")
}
func (UnimplementedAgentServiceServer) CancelRun(context.Context, *CancelRunRequest) (*Run, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedAgentServiceServer) ListRunModels(context.Context, *AgentContentRequest) (*AgentContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRunModels not implemented")
}
func (UnimplementedAgentServiceServer) SetSessionModel(context.Context, *AgentContentRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSessionModel not implemented")
}
func (UnimplementedAgentServiceServer) ListAgentRequests(context.Context, *AgentContentRequest) (*AgentContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgentRequests not implemented")
}
func (UnimplementedAgentServiceServer) GetAgentRequest(context.Context, *AgentContentRequest) (*AgentContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentRequest not implemented")
}
func (UnimplementedAgentServiceServer) CancelAgentRequest(context.Context, *AgentContentRequest) (*AgentContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelAgentRequest not implemented")
}
func (UnimplementedAgentServiceServer) RetryAgentRequest(context.Context, *AgentContentRequest) (*AgentContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryAgentRequest not implemented")
}
func (UnimplementedAgentServiceServer) GetAgentEvidence(context.Context, *AgentContentRequest) (*AgentContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentEvidence not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RefreshServiceInteractionBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RefreshServiceInteractionBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RefreshServiceInteractionBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RefreshServiceInteractionBindings(ctx, req.(*AgentContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Readiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Readiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Readiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Readiness(ctx, req.(*ReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PrepareConfigurationChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareConfigurationChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PrepareConfigurationChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PrepareConfigurationChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PrepareConfigurationChange(ctx, req.(*PrepareConfigurationChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Drain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Drain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Drain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Drain(ctx, req.(*DrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReadSession(ctx, req.(*ReadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SubmitRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SubmitRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SubmitRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SubmitRun(ctx, req.(*SubmitRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_WatchRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).WatchRun(m, &grpc.GenericServerStream[WatchRunRequest, RunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_WatchRunServer = grpc.ServerStreamingServer[RunEvent]

func _AgentService_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListRunModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListRunModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListRunModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListRunModels(ctx, req.(*AgentContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SetSessionModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SetSessionModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SetSessionModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SetSessionModel(ctx, req.(*AgentContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListAgentRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgentRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgentRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgentRequests(ctx, req.(*AgentContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgentRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgentRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgentRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgentRequest(ctx, req.(*AgentContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CancelAgentRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CancelAgentRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CancelAgentRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CancelAgentRequest(ctx, req.(*AgentContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RetryAgentRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RetryAgentRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RetryAgentRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RetryAgentRequest(ctx, req.(*AgentContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgentEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgentEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgentEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgentEvidence(ctx, req.(*AgentContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "piwork.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefreshServiceInteractionBindings",
			Handler:    _AgentService_RefreshServiceInteractionBindings_Handler,
		},
		{
			MethodName: "Readiness",
			Handler:    _AgentService_Readiness_Handler,
		},
		{
			MethodName: "PrepareConfigurationChange",
			Handler:    _AgentService_PrepareConfigurationChange_Handler,
		},
		{
			MethodName: "Drain",
			Handler:    _AgentService_Drain_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _AgentService_CreateSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _AgentService_ListSessions_Handler,
		},
		{
			MethodName: "ReadSession",
			Handler:    _AgentService_ReadSession_Handler,
		},
		{
			MethodName: "SubmitRun",
			Handler:    _AgentService_SubmitRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _AgentService_GetRun_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _AgentService_CancelRun_Handler,
		},
		{
			MethodName: "ListRunModels",
			Handler:    _AgentService_ListRunModels_Handler,
		},
		{
			MethodName: "SetSessionModel",
			Handler:    _AgentService_SetSessionModel_Handler,
		},
		{
			MethodName: "ListAgentRequests",
			Handler:    _AgentService_ListAgentRequests_Handler,
		},
		{
			MethodName: "GetAgentRequest",
			Handler:    _AgentService_GetAgentRequest_Handler,
		},
		{
			MethodName: "CancelAgentRequest",
			Handler:    _AgentService_CancelAgentRequest_Handler,
		},
		{
			MethodName: "RetryAgentRequest",
			Handler:    _AgentService_RetryAgentRequest_Handler,
		},
		{
			MethodName: "GetAgentEvidence",
			Handler:    _AgentService_GetAgentEvidence_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchRun",
			Handler:       _AgentService_WatchRun_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
