export { WorkServicesClient, WorkServicesService } from "./generated/work-services.js";
export {
  CreateServiceRequest as WorkServiceCreateRequestCodec,
  UpdateServiceRequest as WorkServiceUpdateRequestCodec,
  ServiceView as WorkServiceViewCodec,
  OperationView as WorkServiceOperationViewCodec,
  Acceptance as WorkServiceAcceptanceCodec,
} from "./generated/work-services.js";
export type {
  WorkPrivateRequest as RpcWorkPrivateRequest,
  WorkPrivateResponse as RpcWorkPrivateResponse,
  RunModelResolution as RpcRunModelResolution,
  Empty as RpcEmpty,
  ServiceImage as RpcServiceImage,
  ServiceMount as RpcServiceMount,
  ServicePort as RpcServicePort,
  ReadinessProbe as RpcReadinessProbe,
  ServiceDefinition as RpcServiceDefinition,
  ServiceEndpoint as RpcServiceEndpoint,
  SafeError as RpcSafeError,
  ServiceView as RpcServiceView,
  OperationView as RpcOperationView,
  Acceptance as RpcAcceptance,
  DeploymentContext as RpcDeploymentContext,
  CreateServiceRequest as RpcCreateServiceRequest,
  ListServicesResponse as RpcListServicesResponse,
  ServiceIdRequest as RpcServiceIdRequest,
  MutateServiceRequest as RpcMutateServiceRequest,
  UpdateServiceRequest as RpcUpdateServiceRequest,
  OperationIdRequest as RpcOperationIdRequest,
  ReadServiceLogsRequest as RpcReadServiceLogsRequest,
  ServiceLogs as RpcServiceLogs,
  WorkServicesServer,
  WorkServicesClient as WorkServicesClientType,
} from "./generated/work-services.js";
