import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

/**
 * Marks the models.json this daemon owns. A file at the same path without this
 * marker is treated as hand-written and never overwritten.
 */
export const GENERATED_MARKER = "// generated by piwork daemon";

export type ModelsJsonAction = "write" | "keep-user-file";

export interface ModelsJsonPlan {
  action: ModelsJsonAction;
  path: string;
  content: string;
  /** Why the plan skipped writing; logged by the caller. */
  reason?: string;
}

/**
 * Renders the models.json that makes a proxy base url effective.
 *
 * pi reads credentials from the environment but hardcodes each provider's base
 * url, so a proxy address has to be injected through models.json. A provider
 * level baseUrl there replaces the base url of every model under it.
 */
export function renderModelsJson(provider: string, baseUrl: string | undefined): string {
  const header =
    baseUrl === undefined
      ? `${GENERATED_MARKER}: no PIWORK_BASE_URL or ANTHROPIC_BASE_URL was set`
      : `${GENERATED_MARKER} from PIWORK_BASE_URL or ANTHROPIC_BASE_URL`;
  const providers = baseUrl === undefined ? {} : { [provider]: { baseUrl } };
  return `${header}\n${JSON.stringify({ providers }, null, 2)}\n`;
}

export function planModelsJson(options: {
  modelsPath: string;
  provider: string;
  baseUrl: string | undefined;
  existing: string | undefined;
}): ModelsJsonPlan {
  const content = renderModelsJson(options.provider, options.baseUrl);
  if (options.existing !== undefined && !options.existing.includes(GENERATED_MARKER)) {
    return {
      action: "keep-user-file",
      path: options.modelsPath,
      content,
      reason: "existing models.json was not generated by this daemon, leaving it untouched",
    };
  }
  return { action: "write", path: options.modelsPath, content };
}

export async function readIfExists(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

export async function applyModelsJson(plan: ModelsJsonPlan): Promise<void> {
  if (plan.action !== "write") return;
  await mkdir(dirname(plan.path), { recursive: true });
  await writeFile(plan.path, plan.content, "utf8");
}
