import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { GENERATED_MARKER, planModelsJson, renderModelsJson } from "./models-json.js";

const MODELS_PATH = "/demo/.piwork/agent/models.json";

describe("renderModelsJson", () => {
  it("writes a provider level base url so it replaces every model's own base url", () => {
    const rendered = renderModelsJson("anthropic", "https://proxy.example");
    assert.match(rendered, new RegExp(`^${GENERATED_MARKER.replace(/[/\\]/g, "\\$&")}`));
    assert.deepEqual(JSON.parse(rendered.slice(rendered.indexOf("{"))), {
      providers: { anthropic: { baseUrl: "https://proxy.example" } },
    });
  });

  it("writes an empty provider map when no base url is configured", () => {
    const rendered = renderModelsJson("anthropic", undefined);
    assert.deepEqual(JSON.parse(rendered.slice(rendered.indexOf("{"))), { providers: {} });
  });
});

describe("planModelsJson", () => {
  it("writes when no file exists yet", () => {
    const plan = planModelsJson({
      modelsPath: MODELS_PATH,
      provider: "anthropic",
      baseUrl: "https://proxy.example",
      existing: undefined,
    });
    assert.equal(plan.action, "write");
    assert.equal(plan.path, MODELS_PATH);
  });

  it("rewrites a file it previously generated so a removed base url does not linger", () => {
    const existing = renderModelsJson("anthropic", "https://old.example");
    const plan = planModelsJson({
      modelsPath: MODELS_PATH,
      provider: "anthropic",
      baseUrl: undefined,
      existing,
    });
    assert.equal(plan.action, "write");
    assert.deepEqual(JSON.parse(plan.content.slice(plan.content.indexOf("{"))), { providers: {} });
  });

  it("never overwrites a hand-written file", () => {
    const plan = planModelsJson({
      modelsPath: MODELS_PATH,
      provider: "anthropic",
      baseUrl: "https://proxy.example",
      existing: '{ "providers": { "anthropic": { "baseUrl": "https://mine.example" } } }',
    });
    assert.equal(plan.action, "keep-user-file");
    assert.match(plan.reason ?? "", /not generated by this daemon/);
  });
});
