// Code generated by scripts/generate-http-contracts.mjs; DO NOT EDIT.
package contracts

import (
	"encoding/json"
	"os"
	"reflect"
	"strings"
	"testing"
)

func TestGeneratedDTOWireRoundTrip(t *testing.T) {
	raw, err := os.ReadFile("testdata/ts-validation.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixtures []struct {
		Schema string
		Case   string
		JSON   string
	}
	if json.Unmarshal(raw, &fixtures) != nil {
		t.Fatal("invalid fixtures")
	}
	for _, fixture := range fixtures {
		if fixture.Case != "baseline" {
			continue
		}
		t.Run(fixture.Schema, func(t *testing.T) {
			var target any
			switch fixture.Schema {
			case "AcceptedWorkExportSchema":
				value, err := Decode[AcceptedWorkExport](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AcceptedWorkImportSchema":
				value, err := Decode[AcceptedWorkImport](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AcceptedWorkOperationSchema":
				value, err := Decode[AcceptedWorkOperation](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminCreateUserRequestSchema":
				value, err := Decode[AdminCreateUserRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminCredentialResetResultSchema":
				value, err := Decode[AdminCredentialResetResult](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminDefaultWorkPatchSchema":
				value, err := Decode[AdminDefaultWorkPatch](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminDefaultWorkViewSchema":
				value, err := Decode[AdminDefaultWorkView](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminEmptyActionSchema":
				value, err := Decode[AdminEmptyAction](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminErrorSchema":
				value, err := Decode[AdminError](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminPackageDetailSchema":
				value, err := Decode[AdminPackageDetail](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminPackageInstallRequestSchema":
				value, err := Decode[AdminPackageInstallRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminPackageOperationAcceptanceSchema":
				value, err := Decode[AdminPackageOperationAcceptance](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminPackageOperationSchema":
				value, err := Decode[AdminPackageOperation](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminPackageSourceSchema":
				value, err := Decode[AdminPackageSource](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminPackagesSchema":
				value, err := Decode[AdminPackages](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminPackageUpdateRequestSchema":
				value, err := Decode[AdminPackageUpdateRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminPackageUploadResultSchema":
				value, err := Decode[AdminPackageUploadResult](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminResetCredentialRequestSchema":
				value, err := Decode[AdminResetCredentialRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminRuntimeInputSchema":
				value, err := Decode[AdminRuntimeInput](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminRuntimeResultSchema":
				value, err := Decode[AdminRuntimeResult](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminRuntimeViewSchema":
				value, err := Decode[AdminRuntimeView](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminSkillsSchema":
				value, err := Decode[AdminSkills](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminStatusSchema":
				value, err := Decode[AdminStatus](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminUserEnabledResultSchema":
				value, err := Decode[AdminUserEnabledResult](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AdminUsersSchema":
				value, err := Decode[AdminUsers](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AgentEvidenceQuerySchema":
				value, err := Decode[AgentEvidenceQuery](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AgentEvidenceSchema":
				value, err := Decode[AgentEvidence](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AgentRequestDetailSchema":
				value, err := Decode[AgentRequestDetail](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AgentRequestDispositionSchema":
				value, err := Decode[AgentRequestDisposition](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AgentRequestedPayloadSchema":
				value, err := Decode[AgentRequestedPayload](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AgentRequestPageSchema":
				value, err := Decode[AgentRequestPage](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AgentRequestQuerySchema":
				value, err := Decode[AgentRequestQuery](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AgentRequestSchema":
				value, err := Decode[AgentRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AgentRequestStateSchema":
				value, err := Decode[AgentRequestState](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AgentRunSourceSchema":
				value, err := Decode[AgentRunSource](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AgentRuntimeConfigSchema":
				value, err := Decode[AgentRuntimeConfig](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "AgentWaitRefSchema":
				value, err := Decode[AgentWaitRef](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ApiErrorSchema":
				value, err := Decode[ApiError](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ArchivedWorkIdempotencySchema":
				value, err := Decode[ArchivedWorkIdempotency](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ArchivedWorkOperationSchema":
				value, err := Decode[ArchivedWorkOperation](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ArtifactReferenceSchema":
				value, err := Decode[ArtifactReference](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "BrainBehaviorChecksSchema":
				value, err := Decode[BrainBehaviorChecks](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "BrainCandidateSubmissionSchema":
				value, err := Decode[BrainCandidateSubmission](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "BrainVerificationTargetSchema":
				value, err := Decode[BrainVerificationTarget](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "BusinessOperationStateSchema":
				value, err := Decode[BusinessOperationState](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ChatCapabilitiesSchema":
				value, err := Decode[ChatCapabilities](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ChatInputModeSchema":
				value, err := Decode[ChatInputMode](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ChatModelListSchema":
				value, err := Decode[ChatModelList](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ChatModelSchema":
				value, err := Decode[ChatModel](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ChatRunViewSchema":
				value, err := Decode[ChatRunView](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ChatSessionViewSchema":
				value, err := Decode[ChatSessionView](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ChatSubmissionKeySchema":
				value, err := Decode[ChatSubmissionKey](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ChatSubmissionLookupSchema":
				value, err := Decode[ChatSubmissionLookup](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "CreateUserRequestSchema":
				value, err := Decode[CreateUserRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "DiagnosticCodeSchema":
				value, err := Decode[DiagnosticCode](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "DiagnosticCollectionSchema":
				value, err := Decode[DiagnosticCollection](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "DiagnosticStageSchema":
				value, err := Decode[DiagnosticStage](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "DigestSchema":
				value, err := Decode[Digest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ErrorCodeSchema":
				value, err := Decode[ErrorCode](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ExportWorkRequestSchema":
				value, err := Decode[ExportWorkRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "FileAccessCapabilitySchema":
				value, err := Decode[FileAccessCapability](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "FileAccessLimitsSchema":
				value, err := Decode[FileAccessLimits](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "FileHelperAckSchema":
				value, err := Decode[FileHelperAck](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "FileHelperErrorSchema":
				value, err := Decode[FileHelperError](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "FileHelperMetaSchema":
				value, err := Decode[FileHelperMeta](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "FileHelperPreparedSchema":
				value, err := Decode[FileHelperPrepared](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "FileHelperRequestSchema":
				value, err := Decode[FileHelperRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "FileHelperResultSchema":
				value, err := Decode[FileHelperResult](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "IdentifierSchema":
				value, err := Decode[Identifier](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ImageSelectionSchema":
				value, err := Decode[ImageSelection](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ImportWorkRequestSchema":
				value, err := Decode[ImportWorkRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "LookupChatSubmissionSchema":
				value, err := Decode[LookupChatSubmission](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ManagedSkillSchema":
				value, err := Decode[ManagedSkill](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "McpServerSchema":
				value, err := Decode[McpServer](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "OperationDiagnosticsSchema":
				value, err := Decode[OperationDiagnostics](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "OperationSchema":
				value, err := Decode[Operation](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "OperationStateSchema":
				value, err := Decode[OperationState](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "OperatorSkillSchema":
				value, err := Decode[OperatorSkill](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PackageHelperPrepareRequestSchema":
				value, err := Decode[PackageHelperPrepareRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageArtifactMetadataSchema":
				value, err := Decode[PiPackageArtifactMetadata](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageCatalogEntrySchema":
				value, err := Decode[PiPackageCatalogEntry](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageInstallRequestSchema":
				value, err := Decode[PiPackageInstallRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageNameSchema":
				value, err := Decode[PiPackageName](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageOperationAcceptanceSchema":
				value, err := Decode[PiPackageOperationAcceptance](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackagePhaseSchema":
				value, err := Decode[PiPackagePhase](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackagePreparedEnvironmentSchema":
				value, err := Decode[PiPackagePreparedEnvironment](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageResourceCountsSchema":
				value, err := Decode[PiPackageResourceCounts](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageRuntimeStateSchema":
				value, err := Decode[PiPackageRuntimeState](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageSelectionEntrySchema":
				value, err := Decode[PiPackageSelectionEntry](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageSelectionSchema":
				value, err := Decode[PiPackageSelection](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageSourceKindSchema":
				value, err := Decode[PiPackageSourceKind](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageSourceSchema":
				value, err := Decode[PiPackageSource](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageToolPolicyKeySchema":
				value, err := Decode[PiPackageToolPolicyKey](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageUpdateRequestSchema":
				value, err := Decode[PiPackageUpdateRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageUploadResultSchema":
				value, err := Decode[PiPackageUploadResult](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageWorkEntrySchema":
				value, err := Decode[PiPackageWorkEntry](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PiPackageWorkVersionSchema":
				value, err := Decode[PiPackageWorkVersion](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PortableMcpServerSchema":
				value, err := Decode[PortableMcpServer](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PortablePiPackageArtifactSchema":
				value, err := Decode[PortablePiPackageArtifact](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PortableServiceDefinitionSchema":
				value, err := Decode[PortableServiceDefinition](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PortableWorkConfigurationSchema":
				value, err := Decode[PortableWorkConfiguration](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PortableWorkContextSchema":
				value, err := Decode[PortableWorkContext](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PortableWorkImageSchema":
				value, err := Decode[PortableWorkImage](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PortableWorkQuotaReservationSchema":
				value, err := Decode[PortableWorkQuotaReservation](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PortableWorkServiceSchema":
				value, err := Decode[PortableWorkService](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PortableWorkSpecSchema":
				value, err := Decode[PortableWorkSpec](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PublicOperationSchema":
				value, err := Decode[PublicOperation](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "PublicSkillSchema":
				value, err := Decode[PublicSkill](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "QuotaSchema":
				value, err := Decode[Quota](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ReadinessProbeSchema":
				value, err := Decode[ReadinessProbe](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ResetUserPasswordRequestSchema":
				value, err := Decode[ResetUserPasswordRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ResourceIdSchema":
				value, err := Decode[ResourceId](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ResourcePolicySchema":
				value, err := Decode[ResourcePolicy](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "RetryAgentRequestSchema":
				value, err := Decode[RetryAgentRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "RunModelDescriptionSchema":
				value, err := Decode[RunModelDescription](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "RunModelListSchema":
				value, err := Decode[RunModelList](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "RunModelSelectorSchema":
				value, err := Decode[RunModelSelector](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "RunSubmissionSelectorSchema":
				value, err := Decode[RunSubmissionSelector](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "RuntimeSkillSchema":
				value, err := Decode[RuntimeSkill](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "RuntimeSkillStateSchema":
				value, err := Decode[RuntimeSkillState](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SafeDiagnosticSchema":
				value, err := Decode[SafeDiagnostic](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SafeTerminalStageEventSchema":
				value, err := Decode[SafeTerminalStageEvent](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SecretReferenceSchema":
				value, err := Decode[SecretReference](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServiceAccessSchema":
				value, err := Decode[ServiceAccess](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServiceActionResultSchema":
				value, err := Decode[ServiceActionResult](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServiceCapabilitiesSchema":
				value, err := Decode[ServiceCapabilities](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServiceConnectionSchema":
				value, err := Decode[ServiceConnection](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServiceDefinitionInputSchema":
				value, err := Decode[ServiceDefinitionInput](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServiceDefinitionSchema":
				value, err := Decode[ServiceDefinition](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServiceEndpointSchema":
				value, err := Decode[ServiceEndpoint](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServiceEventSchema":
				value, err := Decode[ServiceEvent](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServiceImageSchema":
				value, err := Decode[ServiceImage](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServiceJobResultSchema":
				value, err := Decode[ServiceJobResult](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServiceMountSchema":
				value, err := Decode[ServiceMount](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServicePortSchema":
				value, err := Decode[ServicePort](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ServiceQueryResultSchema":
				value, err := Decode[ServiceQueryResult](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SessionChatOptionsSchema":
				value, err := Decode[SessionChatOptions](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SessionContentBlockSchema":
				value, err := Decode[SessionContentBlock](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SetSessionChatOptionsSchema":
				value, err := Decode[SetSessionChatOptions](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SetSessionModelSchema":
				value, err := Decode[SetSessionModel](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SetWorkAgentsRequestSchema":
				value, err := Decode[SetWorkAgentsRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SetWorkConfigurationRequestSchema":
				value, err := Decode[SetWorkConfigurationRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SetWorkSkillsRequestSchema":
				value, err := Decode[SetWorkSkillsRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SkillNameSchema":
				value, err := Decode[SkillName](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SkillPathRequestSchema":
				value, err := Decode[SkillPathRequest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SkillSelectionSchema":
				value, err := Decode[SkillSelection](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SlashCommandListSchema":
				value, err := Decode[SlashCommandList](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SlashCommandSchema":
				value, err := Decode[SlashCommand](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SnapshotIdempotencyKeySchema":
				value, err := Decode[SnapshotIdempotencyKey](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "SubmitRunInputSchema":
				value, err := Decode[SubmitRunInput](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ThinkingLevelSchema":
				value, err := Decode[ThinkingLevel](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "TimestampSchema":
				value, err := Decode[Timestamp](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ToolPolicySchema":
				value, err := Decode[ToolPolicy](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "ToolResultPreviewSchema":
				value, err := Decode[ToolResultPreview](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "UploadedWorkPackageSchema":
				value, err := Decode[UploadedWorkPackage](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "UserRoleSchema":
				value, err := Decode[UserRole](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "UserSchema":
				value, err := Decode[User](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkBindingRequirementsSchema":
				value, err := Decode[WorkBindingRequirements](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkBlobDigestSchema":
				value, err := Decode[WorkBlobDigest](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkBlobSchema":
				value, err := Decode[WorkBlob](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkByteSizeSchema":
				value, err := Decode[WorkByteSize](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkConfigSchema":
				value, err := Decode[WorkConfig](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkConfigurationPatchSchema":
				value, err := Decode[WorkConfigurationPatch](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkConfigurationViewSchema":
				value, err := Decode[WorkConfigurationView](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkContextIdentitySchema":
				value, err := Decode[WorkContextIdentity](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkContextMetadataSchema":
				value, err := Decode[WorkContextMetadata](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkControlHistorySchema":
				value, err := Decode[WorkControlHistory](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkHistoryMigrationSchema":
				value, err := Decode[WorkHistoryMigration](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkImagePlatformSchema":
				value, err := Decode[WorkImagePlatform](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkImportBindingsSchema":
				value, err := Decode[WorkImportBindings](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkImportProvenanceSchema":
				value, err := Decode[WorkImportProvenance](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkLogicalKeySchema":
				value, err := Decode[WorkLogicalKey](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkReadinessSchema":
				value, err := Decode[WorkReadiness](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkRuntimeIdentitySchema":
				value, err := Decode[WorkRuntimeIdentity](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkSkillStateSchema":
				value, err := Decode[WorkSkillState](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkSnapshotErrorSchema":
				value, err := Decode[WorkSnapshotError](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkSnapshotSchema":
				value, err := Decode[WorkSnapshot](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkSourceIdentityMapSchema":
				value, err := Decode[WorkSourceIdentityMap](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			case "WorkToolPolicyKeySchema":
				value, err := Decode[WorkToolPolicyKey](strings.NewReader(fixture.JSON), fixture.Schema, 2<<20)
				if err != nil {
					t.Fatal(err)
				}
				target = value
			}
			encoded, err := json.Marshal(target)
			if err != nil {
				t.Fatal(err)
			}
			got, err := ParseJSON(strings.NewReader(string(encoded)), 2<<20)
			if err != nil {
				t.Fatal(err)
			}
			want, _ := ParseJSON(strings.NewReader(fixture.JSON), 2<<20)
			if !reflect.DeepEqual(got, want) {
				t.Fatalf("DTO changed wire payload: %s -> %s", fixture.JSON, encoded)
			}
		})
	}
}
