// Code generated by scripts/generate-http-contracts.mjs; DO NOT EDIT.
package contracts

import "encoding/json"

type AcceptedWorkExport struct {
	WorkId        ResourceId `json:"workId"`
	OperationId   ResourceId `json:"operationId"`
	CorrelationId ResourceId `json:"correlationId"`
	Reused        bool       `json:"reused"`
	SnapshotId    ResourceId `json:"snapshotId"`
}

type AcceptedWorkImport struct {
	WorkId        ResourceId `json:"workId"`
	Name          string     `json:"name"`
	OperationId   ResourceId `json:"operationId"`
	CorrelationId ResourceId `json:"correlationId"`
	Reused        bool       `json:"reused"`
}

type AcceptedWorkOperation struct {
	WorkId      ResourceId `json:"workId"`
	OperationId ResourceId `json:"operationId"`
	Reused      bool       `json:"reused"`
}

type AdminCreateUserRequest struct {
	Account  Identifier      `json:"account"`
	Password string          `json:"password"`
	Role     Field[UserRole] `json:"role,omitzero"`
}

type AdminCredentialResetResult struct {
	UserId          ResourceId `json:"userId"`
	CredentialReset bool       `json:"credentialReset"`
}

type AdminDefaultWorkPatch struct {
	BaseImage Field[string]          `json:"baseImage,omitzero"`
	Skills    Field[SkillSelection]  `json:"skills,omitzero"`
	Packages  Field[[]PiPackageName] `json:"packages,omitzero"`
	AgentsMd  Field[string]          `json:"agentsMd,omitzero"`
}

type AdminDefaultWorkView struct {
	Configuration       json.RawMessage `json:"configuration"`
	BaseImage           json.RawMessage `json:"baseImage"`
	BrainInitialization Field[struct {
		State       string            `json:"state"`
		OperationId Field[ResourceId] `json:"operationId,omitzero"`
		Code        Field[string]     `json:"code,omitzero"`
	}] `json:"brainInitialization,omitzero"`
}

type AdminEmptyAction struct {
}

type AdminError struct {
	Code          string        `json:"code"`
	Message       string        `json:"message"`
	CorrelationId ResourceId    `json:"correlationId"`
	Field         Field[string] `json:"field,omitzero"`
	RetryAfterMs  Field[int64]  `json:"retryAfterMs,omitzero"`
}

type AdminPackageDetail struct {
	Name           PiPackageName           `json:"name"`
	Version        json.RawMessage         `json:"version"`
	SourceKind     PiPackageSourceKind     `json:"sourceKind"`
	Enabled        bool                    `json:"enabled"`
	IsDefault      bool                    `json:"isDefault"`
	ResourceCounts PiPackageResourceCounts `json:"resourceCounts"`
	ResolvedSource string                  `json:"resolvedSource"`
}

type AdminPackageInstallRequest struct {
	Source         AdminPackageSource `json:"source"`
	IdempotencyKey string             `json:"idempotencyKey"`
	AddToDefaults  Field[bool]        `json:"addToDefaults,omitzero"`
}

type AdminPackageOperationAcceptance struct {
	OperationId   ResourceId      `json:"operationId"`
	WorkId        json.RawMessage `json:"workId"`
	CorrelationId ResourceId      `json:"correlationId"`
	Reused        bool            `json:"reused"`
	Scope         string          `json:"scope"`
	Kind          string          `json:"kind"`
	Name          json.RawMessage `json:"name"`
}

type AdminPackageOperation struct {
	OperationId  ResourceId      `json:"operationId"`
	WorkId       json.RawMessage `json:"workId"`
	Kind         string          `json:"kind"`
	State        OperationState  `json:"state"`
	PackagePhase PiPackagePhase  `json:"packagePhase"`
	Name         json.RawMessage `json:"name"`
	Result       json.RawMessage `json:"result"`
	Error        json.RawMessage `json:"error"`
	CreatedAt    Timestamp       `json:"createdAt"`
	UpdatedAt    Timestamp       `json:"updatedAt"`
}

type AdminPackageSource = json.RawMessage

type AdminPackages struct {
	Packages []PiPackageCatalogEntry `json:"packages"`
}

type AdminPackageUpdateRequest struct {
	Source         AdminPackageSource `json:"source"`
	IdempotencyKey string             `json:"idempotencyKey"`
}

type AdminPackageUploadResult struct {
	UploadId  ResourceId `json:"uploadId"`
	ExpiresAt Timestamp  `json:"expiresAt"`
}

type AdminResetCredentialRequest struct {
	Password string `json:"password"`
}

type AdminRuntimeInput struct {
	AgentImage string        `json:"agentImage"`
	Provider   string        `json:"provider"`
	Model      string        `json:"model"`
	BaseUrl    Field[string] `json:"baseUrl,omitzero"`
	Credential string        `json:"credential"`
}

type AdminRuntimeResult struct {
	Runtime AdminRuntimeView `json:"runtime"`
	Status  AdminStatus      `json:"status"`
}

type AdminRuntimeView = json.RawMessage

type AdminSkills struct {
	Skills []OperatorSkill `json:"skills"`
}

type AdminStatus struct {
	AdminApiVersion float64 `json:"adminApiVersion"`
	State           string  `json:"state"`
	Ready           bool    `json:"ready"`
	Checks          struct {
		Administrator            bool `json:"administrator"`
		RuntimeConfigured        bool `json:"runtimeConfigured"`
		RuntimeAvailable         bool `json:"runtimeAvailable"`
		FilesystemMigrationReady bool `json:"filesystemMigrationReady"`
	} `json:"checks"`
}

type AdminUserEnabledResult struct {
	UserId  ResourceId `json:"userId"`
	Enabled bool       `json:"enabled"`
}

type AdminUsers struct {
	Users []User `json:"users"`
}

type AgentEvidenceQuery struct {
	Limit  Field[int64]  `json:"limit,omitzero"`
	Cursor Field[string] `json:"cursor,omitzero"`
}

type AgentEvidence struct {
	EvidenceId   Identifier        `json:"evidenceId"`
	RunId        json.RawMessage   `json:"runId"`
	RequestId    json.RawMessage   `json:"requestId"`
	ServiceName  Field[string]     `json:"serviceName,omitzero"`
	Kind         string            `json:"kind"`
	ObjectRef    string            `json:"objectRef"`
	ObservedAt   Timestamp         `json:"observedAt"`
	StateVersion Field[Identifier] `json:"stateVersion,omitzero"`
	CodeVersion  Field[Identifier] `json:"codeVersion,omitzero"`
	Summary      string            `json:"summary"`
	Verified     bool              `json:"verified"`
}

type AgentRequestDetail struct {
	Request  AgentRequest `json:"request"`
	Evidence struct {
		Items      []AgentEvidence `json:"items"`
		NextCursor json.RawMessage `json:"nextCursor"`
	} `json:"evidence"`
	CheckedAt    Timestamp `json:"checkedAt"`
	Availability string    `json:"availability"`
}

type AgentRequestDisposition string

type AgentRequestedPayload struct {
	Reason       string       `json:"reason"`
	Goal         string       `json:"goal"`
	EvidenceRefs []Identifier `json:"evidenceRefs"`
}

type AgentRequestPage struct {
	Items        []AgentRequest  `json:"items"`
	NextCursor   json.RawMessage `json:"nextCursor"`
	CheckedAt    Timestamp       `json:"checkedAt"`
	Availability string          `json:"availability"`
}

type AgentRequestQuery struct {
	ServiceName Field[string]                  `json:"serviceName,omitzero"`
	State       Field[AgentRequestState]       `json:"state,omitzero"`
	Disposition Field[AgentRequestDisposition] `json:"disposition,omitzero"`
	Limit       Field[int64]                   `json:"limit,omitzero"`
	Cursor      Field[string]                  `json:"cursor,omitzero"`
}

type AgentRequest struct {
	RequestId         Identifier              `json:"requestId"`
	Source            AgentRunSource          `json:"source"`
	Goal              string                  `json:"goal"`
	State             AgentRequestState       `json:"state"`
	Disposition       AgentRequestDisposition `json:"disposition"`
	CreatedAt         Timestamp               `json:"createdAt"`
	UpdatedAt         Timestamp               `json:"updatedAt"`
	ExpiresAt         Timestamp               `json:"expiresAt"`
	RetryOf           json.RawMessage         `json:"retryOf"`
	AutoRunCount      int64                   `json:"autoRunCount"`
	WaitRef           json.RawMessage         `json:"waitRef"`
	RunIds            []Identifier            `json:"runIds"`
	EvidenceIds       []Identifier            `json:"evidenceIds"`
	EvidenceCount     Field[int64]            `json:"evidenceCount,omitzero"`
	EvidenceTruncated Field[bool]             `json:"evidenceTruncated,omitzero"`
	Result            json.RawMessage         `json:"result"`
	Error             json.RawMessage         `json:"error"`
}

type AgentRequestState string

type AgentRunSource struct {
	Kind        string            `json:"kind"`
	RequestId   Field[Identifier] `json:"requestId,omitzero"`
	ServiceName Field[string]     `json:"serviceName,omitzero"`
	Phase       Field[string]     `json:"phase,omitzero"`
}

type AgentRuntimeConfig struct {
	Version           float64       `json:"version"`
	WorkId            string        `json:"workId"`
	Generation        int64         `json:"generation"`
	InstanceId        string        `json:"instanceId"`
	Listen            string        `json:"listen"`
	DataDirectory     string        `json:"dataDirectory"`
	Deterministic     bool          `json:"deterministic"`
	ContextConfigPath Field[string] `json:"contextConfigPath,omitzero"`
	Skills            Field[[]struct {
		Name   string `json:"name"`
		Digest string `json:"digest"`
	}] `json:"skills,omitzero"`
	AgentsMdPath       Field[string]   `json:"agentsMdPath,omitzero"`
	ContextIdentity    Field[string]   `json:"contextIdentity,omitzero"`
	ResolvedTools      Field[[]string] `json:"resolvedTools,omitzero"`
	InitializationOnly Field[bool]     `json:"initializationOnly,omitzero"`
	CorrelationId      Field[string]   `json:"correlationId,omitzero"`
	Model              struct {
		Provider       string        `json:"provider"`
		Id             string        `json:"id"`
		BaseUrl        Field[string] `json:"baseUrl,omitzero"`
		CredentialPath Field[string] `json:"credentialPath,omitzero"`
	} `json:"model"`
	Tls struct {
		CaCertificatePath        string `json:"caCertificatePath"`
		ServerCertificatePath    string `json:"serverCertificatePath"`
		ServerPrivateKeyPath     string `json:"serverPrivateKeyPath"`
		ExpectedClientCommonName string `json:"expectedClientCommonName"`
	} `json:"tls"`
	ServiceControl Field[struct {
		Endpoint              string `json:"endpoint"`
		ServerName            string `json:"serverName"`
		CaCertificatePath     string `json:"caCertificatePath"`
		ClientCertificatePath string `json:"clientCertificatePath"`
		ClientPrivateKeyPath  string `json:"clientPrivateKeyPath"`
	}] `json:"serviceControl,omitzero"`
	FeedbackListen Field[string] `json:"feedbackListen,omitzero"`
}

type AgentWaitRef struct {
	Kind             string        `json:"kind"`
	ServiceName      Field[string] `json:"serviceName,omitzero"`
	Id               Identifier    `json:"id"`
	DeadlineAt       Timestamp     `json:"deadlineAt"`
	NextPhase        string        `json:"nextPhase"`
	VerificationGoal string        `json:"verificationGoal"`
}

type ApiError struct {
	Code         string            `json:"code"`
	Message      string            `json:"message"`
	Retryable    bool              `json:"retryable"`
	OperationId  Field[ResourceId] `json:"operationId,omitzero"`
	Field        Field[string]     `json:"field,omitzero"`
	RetryAfterMs Field[int64]      `json:"retryAfterMs,omitzero"`
}

type ArchivedWorkIdempotency struct {
	PrincipalKey   WorkLogicalKey `json:"principalKey"`
	PrincipalKind  string         `json:"principalKind"`
	WorkScope      string         `json:"workScope"`
	OperationKind  string         `json:"operationKind"`
	IdempotencyKey string         `json:"idempotencyKey"`
	RequestDigest  WorkBlobDigest `json:"requestDigest"`
	ResourceId     ResourceId     `json:"resourceId"`
	OperationId    ResourceId     `json:"operationId"`
	CreatedAt      Timestamp      `json:"createdAt"`
}

type ArchivedWorkOperation struct {
	Id            ResourceId      `json:"id"`
	WorkId        ResourceId      `json:"workId"`
	ServiceId     json.RawMessage `json:"serviceId"`
	Kind          string          `json:"kind"`
	State         string          `json:"state"`
	TargetVersion int64           `json:"targetVersion"`
	RequestJson   string          `json:"requestJson"`
	ResultJson    json.RawMessage `json:"resultJson"`
	ErrorJson     json.RawMessage `json:"errorJson"`
	CreatedAt     Timestamp       `json:"createdAt"`
	UpdatedAt     Timestamp       `json:"updatedAt"`
}

type ArtifactReference struct {
	CatalogId ResourceId    `json:"catalogId"`
	Digest    Field[Digest] `json:"digest,omitzero"`
}

type BrainBehaviorChecks []struct {
	Name    string `json:"name"`
	Passed  bool   `json:"passed"`
	Summary string `json:"summary"`
}

type BrainCandidateSubmission struct {
	SubmissionKey        string                  `json:"submissionKey"`
	RequestId            Identifier              `json:"requestId"`
	VerificationGoal     string                  `json:"verificationGoal"`
	VerificationTarget   BrainVerificationTarget `json:"verificationTarget"`
	ExpectedSourceDigest Digest                  `json:"expectedSourceDigest"`
	ActiveDigest         Digest                  `json:"activeDigest"`
	DesiredDigest        Digest                  `json:"desiredDigest"`
	ActiveContextId      Identifier              `json:"activeContextId"`
}

type BrainVerificationTarget struct {
	ContractVersion float64                    `json:"contractVersion"`
	ToolName        string                     `json:"toolName"`
	Input           map[string]json.RawMessage `json:"input"`
	CheckNames      []string                   `json:"checkNames"`
}

type BusinessOperationState string

type CreateUserRequest struct {
	Account  Identifier      `json:"account"`
	Password string          `json:"password"`
	Role     Field[UserRole] `json:"role,omitzero"`
}

type DiagnosticCode string

type DiagnosticCollection struct {
	State string        `json:"state"`
	Code  Field[string] `json:"code,omitzero"`
}

type DiagnosticStage string

type Digest string

type ErrorCode string

type ExportWorkRequest struct {
	IdempotencyKey SnapshotIdempotencyKey `json:"idempotencyKey"`
}

type FileAccessCapability = json.RawMessage

type FileAccessLimits struct {
	MaxHeaderBytes         float64 `json:"maxHeaderBytes"`
	MaxXmlBytes            float64 `json:"maxXmlBytes"`
	MaxXmlDepth            float64 `json:"maxXmlDepth"`
	MaxProperties          float64 `json:"maxProperties"`
	MaxMetadataBytes       float64 `json:"maxMetadataBytes"`
	MaxDirectoryEntries    float64 `json:"maxDirectoryEntries"`
	MaxTreeEntries         float64 `json:"maxTreeEntries"`
	MaxFileBytes           float64 `json:"maxFileBytes"`
	MaxTreeBytes           float64 `json:"maxTreeBytes"`
	MaxSegmentBytes        float64 `json:"maxSegmentBytes"`
	MaxPathBytes           float64 `json:"maxPathBytes"`
	MaxPathDepth           float64 `json:"maxPathDepth"`
	MaxCoreRequests        float64 `json:"maxCoreRequests"`
	MaxUserRequests        float64 `json:"maxUserRequests"`
	MaxWorkRequests        float64 `json:"maxWorkRequests"`
	MaxWorkMutations       float64 `json:"maxWorkMutations"`
	ConnectTimeoutMs       float64 `json:"connectTimeoutMs"`
	HelperTimeoutMs        float64 `json:"helperTimeoutMs"`
	IdleTimeoutMs          float64 `json:"idleTimeoutMs"`
	RequestTimeoutMs       float64 `json:"requestTimeoutMs"`
	AuthorizationRecheckMs float64 `json:"authorizationRecheckMs"`
}

type FileHelperAck struct {
	Epoch       int64           `json:"epoch"`
	Phase       string          `json:"phase"`
	TemporaryId json.RawMessage `json:"temporaryId"`
}

type FileHelperError struct {
	Code         string          `json:"code"`
	PathSegments json.RawMessage `json:"pathSegments"`
}

type FileHelperMeta struct {
	PathSegments []string        `json:"pathSegments"`
	Kind         string          `json:"kind"`
	Size         json.RawMessage `json:"size"`
	ModifiedMs   json.RawMessage `json:"modifiedMs"`
}

type FileHelperPrepared struct {
	Epoch          int64           `json:"epoch"`
	Phase          string          `json:"phase"`
	TemporaryId    json.RawMessage `json:"temporaryId"`
	ParentSegments []string        `json:"parentSegments"`
	Name           json.RawMessage `json:"name"`
	Device         json.RawMessage `json:"device"`
	Inode          json.RawMessage `json:"inode"`
}

type FileHelperRequest struct {
	Version             float64         `json:"version"`
	JobId               ResourceId      `json:"jobId"`
	WorkId              ResourceId      `json:"workId"`
	Epoch               int64           `json:"epoch"`
	Action              string          `json:"action"`
	PathSegments        []string        `json:"pathSegments"`
	DestinationSegments json.RawMessage `json:"destinationSegments"`
	Depth               json.RawMessage `json:"depth"`
	Overwrite           json.RawMessage `json:"overwrite"`
	Conditions          struct {
		IfMatch           json.RawMessage `json:"ifMatch"`
		IfNoneMatch       json.RawMessage `json:"ifNoneMatch"`
		IfModifiedSince   json.RawMessage `json:"ifModifiedSince"`
		IfUnmodifiedSince json.RawMessage `json:"ifUnmodifiedSince"`
	} `json:"conditions"`
	Range          json.RawMessage `json:"range"`
	ExpectedLength json.RawMessage `json:"expectedLength"`
	Temporaries    Field[[]struct {
		TemporaryId    ResourceId `json:"temporaryId"`
		ParentSegments []string   `json:"parentSegments"`
		Name           string     `json:"name"`
		Device         string     `json:"device"`
		Inode          string     `json:"inode"`
	}] `json:"temporaries,omitzero"`
}

type FileHelperResult struct {
	Status  int64 `json:"status"`
	Bytes   int64 `json:"bytes"`
	Entries int64 `json:"entries"`
}

type Identifier string

type ImageSelection struct {
	CatalogId ResourceId `json:"catalogId"`
}

type ImportWorkRequest struct {
	PackageId      ResourceId             `json:"packageId"`
	Name           Field[string]          `json:"name,omitzero"`
	IdempotencyKey SnapshotIdempotencyKey `json:"idempotencyKey"`
}

type ManagedSkill struct {
	Name       SkillName `json:"name"`
	Enabled    bool      `json:"enabled"`
	FileCount  int64     `json:"fileCount"`
	TotalBytes int64     `json:"totalBytes"`
	CreatedAt  Timestamp `json:"createdAt"`
	UpdatedAt  Timestamp `json:"updatedAt"`
}

type McpServer struct {
	ServerId          Identifier               `json:"serverId"`
	Transport         string                   `json:"transport"`
	Required          bool                     `json:"required"`
	Command           Field[string]            `json:"command,omitzero"`
	Args              Field[[]string]          `json:"args,omitzero"`
	Url               Field[string]            `json:"url,omitzero"`
	TimeoutMs         Field[int64]             `json:"timeoutMs,omitzero"`
	SecretRefs        Field[[]SecretReference] `json:"secretRefs,omitzero"`
	RequiredServiceId Field[ResourceId]        `json:"requiredServiceId,omitzero"`
}

type OperationDiagnostics struct {
	Stages    []SafeTerminalStageEvent `json:"stages"`
	Truncated bool                     `json:"truncated"`
	Rollback  struct {
		State string                `json:"state"`
		Error Field[SafeDiagnostic] `json:"error,omitzero"`
	} `json:"rollback"`
	DiagnosticCollection DiagnosticCollection `json:"diagnosticCollection"`
}

type Operation struct {
	Id            ResourceId      `json:"id"`
	WorkId        ResourceId      `json:"workId"`
	Kind          string          `json:"kind"`
	State         OperationState  `json:"state"`
	TargetVersion int64           `json:"targetVersion"`
	CreatedAt     Timestamp       `json:"createdAt"`
	UpdatedAt     Timestamp       `json:"updatedAt"`
	Error         Field[ApiError] `json:"error,omitzero"`
}

type OperationState string

type OperatorSkill struct {
	Name       SkillName `json:"name"`
	Enabled    bool      `json:"enabled"`
	FileCount  int64     `json:"fileCount"`
	TotalBytes int64     `json:"totalBytes"`
	CreatedAt  Timestamp `json:"createdAt"`
	UpdatedAt  Timestamp `json:"updatedAt"`
}

type PackageHelperPrepareRequest struct {
	Source json.RawMessage `json:"source"`
}

type PiPackageArtifactMetadata struct {
	Name                PiPackageName                `json:"name"`
	Version             json.RawMessage              `json:"version"`
	SourceKind          PiPackageSourceKind          `json:"sourceKind"`
	ResolvedSource      string                       `json:"resolvedSource"`
	PreparedEnvironment PiPackagePreparedEnvironment `json:"preparedEnvironment"`
	ResourceCounts      PiPackageResourceCounts      `json:"resourceCounts"`
	ContentDigest       Digest                       `json:"contentDigest"`
}

type PiPackageCatalogEntry struct {
	Name           PiPackageName           `json:"name"`
	Version        json.RawMessage         `json:"version"`
	SourceKind     PiPackageSourceKind     `json:"sourceKind"`
	Enabled        bool                    `json:"enabled"`
	IsDefault      bool                    `json:"isDefault"`
	ResourceCounts PiPackageResourceCounts `json:"resourceCounts"`
}

type PiPackageInstallRequest struct {
	Source         PiPackageSource `json:"source"`
	AddToDefaults  Field[bool]     `json:"addToDefaults,omitzero"`
	IdempotencyKey string          `json:"idempotencyKey"`
}

type PiPackageName string

type PiPackageOperationAcceptance struct {
	OperationId   ResourceId      `json:"operationId"`
	WorkId        json.RawMessage `json:"workId"`
	CorrelationId ResourceId      `json:"correlationId"`
	Reused        bool            `json:"reused"`
	Scope         string          `json:"scope"`
	Kind          string          `json:"kind"`
	Name          json.RawMessage `json:"name"`
}

type PiPackagePhase string

type PiPackagePreparedEnvironment struct {
	Os           string          `json:"os"`
	Architecture string          `json:"architecture"`
	Variant      json.RawMessage `json:"variant"`
	NodeAbi      string          `json:"nodeAbi"`
	PiSdkVersion string          `json:"piSdkVersion"`
}

type PiPackageResourceCounts struct {
	Extensions int64 `json:"extensions"`
	Skills     int64 `json:"skills"`
	Prompts    int64 `json:"prompts"`
	Themes     int64 `json:"themes"`
}

type PiPackageRuntimeState struct {
	Availability string          `json:"availability"`
	Loaded       json.RawMessage `json:"loaded"`
	Diagnostics  []string        `json:"diagnostics"`
}

type PiPackageSelectionEntry struct {
	Name    PiPackageName `json:"name"`
	Enabled bool          `json:"enabled"`
}

type PiPackageSelection []PiPackageSelectionEntry

type PiPackageSourceKind string

type PiPackageSource = json.RawMessage

type PiPackageToolPolicyKey string

type PiPackageUpdateRequest struct {
	Source         PiPackageSource `json:"source"`
	IdempotencyKey string          `json:"idempotencyKey"`
}

type PiPackageUploadResult struct {
	UploadId  ResourceId `json:"uploadId"`
	ExpiresAt Timestamp  `json:"expiresAt"`
}

type PiPackageWorkEntry struct {
	Name         PiPackageName         `json:"name"`
	Desired      json.RawMessage       `json:"desired"`
	Active       json.RawMessage       `json:"active"`
	PendingApply bool                  `json:"pendingApply"`
	Runtime      PiPackageRuntimeState `json:"runtime"`
	Candidate    Field[struct {
		Source      string     `json:"source"`
		OperationId ResourceId `json:"operationId"`
		RequestId   Identifier `json:"requestId"`
		Preparation string     `json:"preparation"`
		Desired     bool       `json:"desired"`
		Active      bool       `json:"active"`
		Adoption    string     `json:"adoption"`
		Baseline    struct {
			ActiveSelected        bool `json:"activeSelected"`
			DesiredSelected       bool `json:"desiredSelected"`
			ActiveMatchesCurrent  bool `json:"activeMatchesCurrent"`
			DesiredMatchesCurrent bool `json:"desiredMatchesCurrent"`
		} `json:"baseline"`
		Verification struct {
			Goal         string   `json:"goal"`
			ToolName     string   `json:"toolName"`
			InputSummary string   `json:"inputSummary"`
			CheckNames   []string `json:"checkNames"`
		} `json:"verification"`
		Apply struct {
			Availability string                `json:"availability"`
			OperationId  Field[ResourceId]     `json:"operationId,omitzero"`
			State        Field[OperationState] `json:"state,omitzero"`
			Error        Field[struct {
				Code    string `json:"code"`
				Message string `json:"message"`
			}] `json:"error,omitzero"`
		} `json:"apply"`
	}] `json:"candidate,omitzero"`
}

type PiPackageWorkVersion struct {
	Version json.RawMessage `json:"version"`
	Enabled bool            `json:"enabled"`
}

type PortableMcpServer struct {
	ServerId           Identifier            `json:"serverId"`
	Transport          string                `json:"transport"`
	Required           bool                  `json:"required"`
	Command            Field[string]         `json:"command,omitzero"`
	Args               Field[[]string]       `json:"args,omitzero"`
	Url                Field[string]         `json:"url,omitzero"`
	TimeoutMs          Field[int64]          `json:"timeoutMs,omitzero"`
	RequiredServiceKey Field[WorkLogicalKey] `json:"requiredServiceKey,omitzero"`
	SecretRefs         Field[[]struct {
		BindingKey WorkLogicalKey    `json:"bindingKey"`
		Key        Field[Identifier] `json:"key,omitzero"`
	}] `json:"secretRefs,omitzero"`
}

type PortablePiPackageArtifact struct {
	Key                 Digest                       `json:"key"`
	Name                PiPackageName                `json:"name"`
	Version             json.RawMessage              `json:"version"`
	SourceKind          PiPackageSourceKind          `json:"sourceKind"`
	ResolvedSource      string                       `json:"resolvedSource"`
	PreparedEnvironment PiPackagePreparedEnvironment `json:"preparedEnvironment"`
	ResourceCounts      PiPackageResourceCounts      `json:"resourceCounts"`
	ContentDigest       Digest                       `json:"contentDigest"`
	TreeDigest          WorkBlobDigest               `json:"treeDigest"`
	ResourceInventory   struct {
		Extensions []string `json:"extensions"`
		Skills     []string `json:"skills"`
		Prompts    []string `json:"prompts"`
		Themes     []string `json:"themes"`
	} `json:"resourceInventory"`
}

type PortableServiceDefinition struct {
	Name             string                     `json:"name"`
	Image            ServiceImage               `json:"image"`
	Command          string                     `json:"command"`
	Args             []string                   `json:"args"`
	Environment      map[string]json.RawMessage `json:"environment"`
	SecretRefs       []json.RawMessage          `json:"secretRefs"`
	WorkingDirectory string                     `json:"workingDirectory"`
	Mounts           []ServiceMount             `json:"mounts"`
	Ports            []ServicePort              `json:"ports"`
	CpuMillis        int64                      `json:"cpuMillis"`
	MemoryBytes      int64                      `json:"memoryBytes"`
	Enabled          bool                       `json:"enabled"`
	Required         bool                       `json:"required"`
	Readiness        Field[ReadinessProbe]      `json:"readiness,omitzero"`
	RestartPolicy    string                     `json:"restartPolicy"`
}

type PortableWorkConfiguration struct {
	Skills          SkillSelection      `json:"skills"`
	Packages        PiPackageSelection  `json:"packages"`
	Resources       ResourcePolicy      `json:"resources"`
	Tools           ToolPolicy          `json:"tools"`
	ModelBindingKey WorkLogicalKey      `json:"modelBindingKey"`
	McpServers      []PortableMcpServer `json:"mcpServers"`
}

type PortableWorkContext struct {
	Key             WorkLogicalKey            `json:"key"`
	CreatedAt       Timestamp                 `json:"createdAt"`
	Configuration   PortableWorkConfiguration `json:"configuration"`
	SkillsTree      WorkBlobDigest            `json:"skillsTree"`
	AgentsBlob      WorkBlobDigest            `json:"agentsBlob"`
	ImageKey        WorkLogicalKey            `json:"imageKey"`
	PackageBindings []struct {
		Name        PiPackageName `json:"name"`
		ArtifactKey Digest        `json:"artifactKey"`
	} `json:"packageBindings"`
}

type PortableWorkImage struct {
	Key      WorkLogicalKey    `json:"key"`
	ImageId  Digest            `json:"imageId"`
	Platform WorkImagePlatform `json:"platform"`
	Config   WorkBlobDigest    `json:"config"`
	Layers   []WorkBlobDigest  `json:"layers"`
}

type PortableWorkQuotaReservation struct {
	SubjectKind        string         `json:"subjectKind"`
	SubjectKey         WorkLogicalKey `json:"subjectKey"`
	DesiredCpuMillis   WorkByteSize   `json:"desiredCpuMillis"`
	DesiredMemoryBytes WorkByteSize   `json:"desiredMemoryBytes"`
	ServiceSlots       WorkByteSize   `json:"serviceSlots"`
	VolumeSlots        WorkByteSize   `json:"volumeSlots"`
}

type PortableWorkService struct {
	Key             WorkLogicalKey  `json:"key"`
	Name            string          `json:"name"`
	DesiredRevision int64           `json:"desiredRevision"`
	AppliedRevision json.RawMessage `json:"appliedRevision"`
	Enabled         bool            `json:"enabled"`
	TombstonedAt    json.RawMessage `json:"tombstonedAt"`
	Revisions       []struct {
		Revision   int64                     `json:"revision"`
		CreatedAt  Timestamp                 `json:"createdAt"`
		Definition PortableServiceDefinition `json:"definition"`
		ImageKey   json.RawMessage           `json:"imageKey"`
	} `json:"revisions"`
	Recovery struct {
		Count           WorkByteSize    `json:"count"`
		WindowStartedAt json.RawMessage `json:"windowStartedAt"`
		NextRetryAt     json.RawMessage `json:"nextRetryAt"`
		ReadySince      json.RawMessage `json:"readySince"`
	} `json:"recovery"`
	SourceObservation struct {
		State     string          `json:"state"`
		LastError json.RawMessage `json:"lastError"`
	} `json:"sourceObservation"`
}

type PortableWorkSpec struct {
	FormatVersion float64 `json:"formatVersion"`
	SnapshotKind  string  `json:"snapshotKind"`
	CreatedAt     string  `json:"createdAt"`
	SourceName    string  `json:"sourceName"`
	Compatibility struct {
		Os                string          `json:"os"`
		Architecture      string          `json:"architecture"`
		Variant           json.RawMessage `json:"variant"`
		AgentProtocol     string          `json:"agentProtocol"`
		WorkHistorySchema float64         `json:"workHistorySchema"`
		StorageLayout     float64         `json:"storageLayout"`
		PiPackageContract float64         `json:"piPackageContract"`
	} `json:"compatibility"`
	ActiveContext      json.RawMessage                `json:"activeContext"`
	DesiredContext     WorkLogicalKey                 `json:"desiredContext"`
	Contexts           []PortableWorkContext          `json:"contexts"`
	PiPackageArtifacts []PortablePiPackageArtifact    `json:"piPackageArtifacts"`
	Services           []PortableWorkService          `json:"services"`
	QuotaReservations  []PortableWorkQuotaReservation `json:"quotaReservations"`
	Images             []PortableWorkImage            `json:"images"`
	Volumes            []json.RawMessage              `json:"volumes"`
	Bindings           WorkBindingRequirements        `json:"bindings"`
	History            struct {
		Control           WorkBlobDigest `json:"control"`
		SourceIdentityMap WorkBlobDigest `json:"sourceIdentityMap"`
	} `json:"history"`
	Blobs []WorkBlob `json:"blobs"`
}

type PublicOperation struct {
	OperationId   ResourceId            `json:"operationId"`
	WorkId        ResourceId            `json:"workId"`
	Kind          string                `json:"kind"`
	PackagePhase  Field[PiPackagePhase] `json:"packagePhase,omitzero"`
	State         OperationState        `json:"state"`
	CreatedAt     Timestamp             `json:"createdAt"`
	UpdatedAt     Timestamp             `json:"updatedAt"`
	CorrelationId ResourceId            `json:"correlationId"`
	Result        json.RawMessage       `json:"result"`
	Error         json.RawMessage       `json:"error"`
	Diagnostics   OperationDiagnostics  `json:"diagnostics"`
	PackageSource Field[struct {
		Kind      string     `json:"kind"`
		Label     string     `json:"label"`
		RequestId ResourceId `json:"requestId"`
	}] `json:"packageSource,omitzero"`
}

type PublicSkill struct {
	Name SkillName `json:"name"`
}

type Quota struct {
	MaxWorks                  int64 `json:"maxWorks"`
	MaxServicesPerWork        int64 `json:"maxServicesPerWork"`
	MaxRetainedVolumesPerWork int64 `json:"maxRetainedVolumesPerWork"`
	TotalCpuMillis            int64 `json:"totalCpuMillis"`
	TotalMemoryBytes          int64 `json:"totalMemoryBytes"`
}

type ReadinessProbe struct {
	Kind       string            `json:"kind"`
	PortName   Field[Identifier] `json:"portName,omitzero"`
	Path       Field[string]     `json:"path,omitzero"`
	Command    Field[[]string]   `json:"command,omitzero"`
	DeadlineMs Field[int64]      `json:"deadlineMs,omitzero"`
	TimeoutMs  Field[int64]      `json:"timeoutMs,omitzero"`
}

type ResetUserPasswordRequest struct {
	Password string `json:"password"`
}

type ResourceId string

type ResourcePolicy struct {
	CpuMillis          int64 `json:"cpuMillis"`
	MemoryBytes        int64 `json:"memoryBytes"`
	AgentCpuMillis     int64 `json:"agentCpuMillis"`
	AgentMemoryBytes   int64 `json:"agentMemoryBytes"`
	MaxServices        int64 `json:"maxServices"`
	MaxRetainedVolumes int64 `json:"maxRetainedVolumes"`
}

type RetryAgentRequest struct {
	SubmissionKey string `json:"submissionKey"`
}

type RunModelDescription struct {
	ModelRef json.RawMessage `json:"modelRef"`
	Label    string          `json:"label"`
	Provider string          `json:"provider"`
	Model    string          `json:"model"`
}

type RunModelList struct {
	Models       []RunModelDescription `json:"models"`
	DefaultModel RunModelDescription   `json:"defaultModel"`
	CheckedAt    Timestamp             `json:"checkedAt"`
	Availability string                `json:"availability"`
}

type RunModelSelector = json.RawMessage

type RuntimeSkill struct {
	Name             SkillName       `json:"name"`
	Loaded           bool            `json:"loaded"`
	ModelVisible     bool            `json:"modelVisible"`
	VisibilityReason json.RawMessage `json:"visibilityReason"`
}

type RuntimeSkillState struct {
	State     string          `json:"state"`
	CheckedAt json.RawMessage `json:"checkedAt"`
	Skills    []RuntimeSkill  `json:"skills"`
	Packages  Field[[]struct {
		Name        PiPackageName `json:"name"`
		Loaded      bool          `json:"loaded"`
		Diagnostics []string      `json:"diagnostics"`
	}] `json:"packages,omitzero"`
}

type SafeDiagnostic struct {
	Code          DiagnosticCode    `json:"code"`
	Stage         DiagnosticStage   `json:"stage"`
	Message       string            `json:"message"`
	Retryable     bool              `json:"retryable"`
	Remediation   string            `json:"remediation"`
	Field         Field[string]     `json:"field,omitzero"`
	SkillName     Field[SkillName]  `json:"skillName,omitzero"`
	ServiceId     Field[ResourceId] `json:"serviceId,omitzero"`
	CorrelationId Field[ResourceId] `json:"correlationId,omitzero"`
	ExitCode      Field[int64]      `json:"exitCode,omitzero"`
}

type SafeTerminalStageEvent struct {
	Timestamp Timestamp         `json:"timestamp"`
	Component string            `json:"component"`
	Stage     DiagnosticStage   `json:"stage"`
	Outcome   string            `json:"outcome"`
	Code      DiagnosticCode    `json:"code"`
	Message   string            `json:"message"`
	SkillName Field[SkillName]  `json:"skillName,omitzero"`
	ServiceId Field[ResourceId] `json:"serviceId,omitzero"`
}

type SecretReference struct {
	SecretId ResourceId        `json:"secretId"`
	Key      Field[Identifier] `json:"key,omitzero"`
}

type ServiceAccess struct {
	Hostname        string          `json:"hostname"`
	DefaultUrl      json.RawMessage `json:"defaultUrl"`
	DefaultPortName json.RawMessage `json:"defaultPortName"`
	Status          string          `json:"status"`
	Ports           []struct {
		Name Identifier `json:"name"`
		Port int64      `json:"port"`
		Url  string     `json:"url"`
	} `json:"ports"`
}

type ServiceActionResult struct {
	ActionId             Identifier             `json:"actionId"`
	ActionName           string                 `json:"actionName"`
	Input                json.RawMessage        `json:"input"`
	ExpectedStateVersion json.RawMessage        `json:"expectedStateVersion"`
	State                BusinessOperationState `json:"state"`
	StateVersion         Identifier             `json:"stateVersion"`
	ObservedAt           Timestamp              `json:"observedAt"`
	Result               Field[json.RawMessage] `json:"result,omitzero"`
	JobId                Field[json.RawMessage] `json:"jobId,omitzero"`
	Error                Field[struct {
		Code    Identifier `json:"code"`
		Message string     `json:"message"`
	}] `json:"error,omitzero"`
}

type ServiceCapabilities struct {
	ContractVersion    float64                    `json:"contractVersion"`
	LogicalServiceName string                     `json:"logicalServiceName"`
	CodeVersion        Identifier                 `json:"codeVersion"`
	StateVersion       Identifier                 `json:"stateVersion"`
	Queries            map[string]json.RawMessage `json:"queries"`
	Actions            map[string]json.RawMessage `json:"actions"`
	Events             struct {
		Facts          []string `json:"facts"`
		RequestReasons []string `json:"requestReasons"`
	} `json:"events"`
	Jobs bool `json:"jobs"`
}

type ServiceConnection struct {
	ContractVersion float64 `json:"contractVersion"`
	ServiceName     string  `json:"serviceName"`
	ApiPortName     string  `json:"apiPortName"`
	Mode            string  `json:"mode"`
}

type ServiceDefinitionInput struct {
	Name             string                            `json:"name"`
	Image            ServiceImage                      `json:"image"`
	Command          string                            `json:"command"`
	Args             Field[[]string]                   `json:"args,omitzero"`
	Environment      Field[map[string]json.RawMessage] `json:"environment,omitzero"`
	SecretRefs       Field[[]json.RawMessage]          `json:"secretRefs,omitzero"`
	WorkingDirectory Field[string]                     `json:"workingDirectory,omitzero"`
	Mounts           Field[[]ServiceMount]             `json:"mounts,omitzero"`
	Ports            Field[[]ServicePort]              `json:"ports,omitzero"`
	CpuMillis        Field[int64]                      `json:"cpuMillis,omitzero"`
	MemoryBytes      Field[int64]                      `json:"memoryBytes,omitzero"`
	Enabled          Field[bool]                       `json:"enabled,omitzero"`
	Required         Field[bool]                       `json:"required,omitzero"`
	Readiness        Field[ReadinessProbe]             `json:"readiness,omitzero"`
	RestartPolicy    Field[string]                     `json:"restartPolicy,omitzero"`
}

type ServiceDefinition struct {
	ServiceId        ResourceId                 `json:"serviceId"`
	Revision         int64                      `json:"revision"`
	Name             string                     `json:"name"`
	Image            ServiceImage               `json:"image"`
	Command          string                     `json:"command"`
	Args             []string                   `json:"args"`
	Environment      map[string]json.RawMessage `json:"environment"`
	SecretRefs       []json.RawMessage          `json:"secretRefs"`
	WorkingDirectory string                     `json:"workingDirectory"`
	Mounts           []ServiceMount             `json:"mounts"`
	Ports            []ServicePort              `json:"ports"`
	CpuMillis        int64                      `json:"cpuMillis"`
	MemoryBytes      int64                      `json:"memoryBytes"`
	Enabled          bool                       `json:"enabled"`
	Required         bool                       `json:"required"`
	Readiness        Field[ReadinessProbe]      `json:"readiness,omitzero"`
	RestartPolicy    string                     `json:"restartPolicy"`
}

type ServiceEndpoint struct {
	Name     Identifier    `json:"name"`
	Protocol string        `json:"protocol"`
	Host     string        `json:"host"`
	Port     int64         `json:"port"`
	Url      Field[string] `json:"url,omitzero"`
}

type ServiceEvent struct {
	ContractVersion float64    `json:"contractVersion"`
	EventId         Identifier `json:"eventId"`
	Origin          struct {
		WorkId    ResourceId `json:"workId"`
		ServiceId ResourceId `json:"serviceId"`
	} `json:"origin"`
	ServiceName        string                     `json:"serviceName"`
	Type               string                     `json:"type"`
	OccurredAt         Timestamp                  `json:"occurredAt"`
	StateVersion       Identifier                 `json:"stateVersion"`
	EntityRef          Field[json.RawMessage]     `json:"entityRef,omitzero"`
	ActionId           Field[json.RawMessage]     `json:"actionId,omitzero"`
	JobId              Field[json.RawMessage]     `json:"jobId,omitzero"`
	CausationRequestId Field[json.RawMessage]     `json:"causationRequestId,omitzero"`
	Actor              Field[string]              `json:"actor,omitzero"`
	Payload            map[string]json.RawMessage `json:"payload"`
}

type ServiceImage struct {
	Reference string `json:"reference"`
}

type ServiceJobResult struct {
	JobId      Identifier             `json:"jobId"`
	ActionId   Identifier             `json:"actionId"`
	State      BusinessOperationState `json:"state"`
	ObservedAt Timestamp              `json:"observedAt"`
	DeadlineAt Timestamp              `json:"deadlineAt"`
	Artifacts  []string               `json:"artifacts"`
	Result     Field[json.RawMessage] `json:"result,omitzero"`
	Error      Field[struct {
		Code    Identifier `json:"code"`
		Message string     `json:"message"`
	}] `json:"error,omitzero"`
}

type ServiceMount struct {
	Source   string `json:"source"`
	Target   string `json:"target"`
	ReadOnly bool   `json:"readOnly"`
}

type ServicePort struct {
	Name          Identifier `json:"name"`
	ContainerPort int64      `json:"containerPort"`
	Protocol      string     `json:"protocol"`
}

type ServiceQueryResult struct {
	StateVersion Identifier      `json:"stateVersion"`
	CodeVersion  Identifier      `json:"codeVersion"`
	ObservedAt   Timestamp       `json:"observedAt"`
	Value        json.RawMessage `json:"value"`
	Checks       Field[[]struct {
		Name    Identifier `json:"name"`
		Passed  bool       `json:"passed"`
		Summary string     `json:"summary"`
	}] `json:"checks,omitzero"`
}

type SetSessionModel struct {
	ModelRef json.RawMessage `json:"modelRef"`
}

type SetWorkAgentsRequest struct {
	AgentsMd string `json:"agentsMd"`
}

type SetWorkConfigurationRequest struct {
	Configuration WorkConfig `json:"configuration"`
}

type SetWorkSkillsRequest struct {
	Skills SkillSelection `json:"skills"`
}

type SkillName string

type SkillPathRequest struct {
	Path string `json:"path"`
}

type SkillSelection []SkillName

type SnapshotIdempotencyKey string

type SubmitRunInput struct {
	SessionId     Identifier             `json:"sessionId"`
	SubmissionKey string                 `json:"submissionKey"`
	Prompt        string                 `json:"prompt"`
	ModelRef      Field[json.RawMessage] `json:"modelRef,omitzero"`
}

type Timestamp string

type ToolPolicy struct {
	Allowed []WorkToolPolicyKey `json:"allowed"`
	Denied  []WorkToolPolicyKey `json:"denied"`
}

type UploadedWorkPackage struct {
	PackageId           ResourceId              `json:"packageId"`
	Digest              WorkBlobDigest          `json:"digest"`
	Size                WorkByteSize            `json:"size"`
	ExpiresAt           Timestamp               `json:"expiresAt"`
	BindingRequirements WorkBindingRequirements `json:"bindingRequirements"`
}

type UserRole string

type User struct {
	Id        ResourceId `json:"id"`
	Account   Identifier `json:"account"`
	Role      UserRole   `json:"role"`
	Enabled   bool       `json:"enabled"`
	CreatedAt Timestamp  `json:"createdAt"`
	UpdatedAt Timestamp  `json:"updatedAt"`
}

type WorkBindingRequirements struct {
	Models []struct {
		Key      WorkLogicalKey  `json:"key"`
		Provider string          `json:"provider"`
		Model    string          `json:"model"`
		BaseUrl  json.RawMessage `json:"baseUrl"`
	} `json:"models"`
	Secrets []struct {
		Key  WorkLogicalKey `json:"key"`
		Uses []struct {
			ContextKey WorkLogicalKey  `json:"contextKey"`
			ServerId   Identifier      `json:"serverId"`
			Key        json.RawMessage `json:"key"`
		} `json:"uses"`
	} `json:"secrets"`
}

type WorkBlobDigest string

type WorkBlob struct {
	Digest WorkBlobDigest `json:"digest"`
	Size   WorkByteSize   `json:"size"`
	Kinds  []string       `json:"kinds"`
}

type WorkByteSize int64

type WorkConfig struct {
	AgentImage ImageSelection     `json:"agentImage"`
	Skills     SkillSelection     `json:"skills"`
	Packages   PiPackageSelection `json:"packages"`
	AgentsMd   string             `json:"agentsMd"`
	ModelRef   ResourceId         `json:"modelRef"`
	McpServers []McpServer        `json:"mcpServers"`
	Resources  ResourcePolicy     `json:"resources"`
	Tools      ToolPolicy         `json:"tools"`
}

type WorkConfigurationPatch struct {
	AgentImage Field[ImageSelection]     `json:"agentImage,omitzero"`
	Skills     Field[SkillSelection]     `json:"skills,omitzero"`
	Packages   Field[PiPackageSelection] `json:"packages,omitzero"`
	AgentsMd   Field[string]             `json:"agentsMd,omitzero"`
	ModelRef   Field[ResourceId]         `json:"modelRef,omitzero"`
	McpServers Field[[]McpServer]        `json:"mcpServers,omitzero"`
	Resources  Field[ResourcePolicy]     `json:"resources,omitzero"`
	Tools      Field[ToolPolicy]         `json:"tools,omitzero"`
}

type WorkConfigurationView struct {
	WorkId       ResourceId        `json:"workId"`
	Active       json.RawMessage   `json:"active"`
	Desired      WorkConfig        `json:"desired"`
	PendingApply bool              `json:"pendingApply"`
	Runtime      RuntimeSkillState `json:"runtime"`
}

type WorkContextIdentity string

type WorkContextMetadata struct {
	Version       float64 `json:"version"`
	SnapshotId    string  `json:"snapshotId"`
	WorkId        string  `json:"workId"`
	ImageIdentity Digest  `json:"imageIdentity"`
	Skills        []struct {
		Name     string `json:"name"`
		Identity string `json:"identity"`
	} `json:"skills"`
	PackageContractVersion float64 `json:"packageContractVersion"`
	PackageBindings        []struct {
		Name     string                    `json:"name"`
		NameKey  string                    `json:"nameKey"`
		Artifact PiPackageArtifactMetadata `json:"artifact"`
	} `json:"packageBindings"`
	CreatedAt Timestamp `json:"createdAt"`
}

type WorkControlHistory struct {
	Version float64 `json:"version"`
	Work    struct {
		Name      string    `json:"name"`
		CreatedAt Timestamp `json:"createdAt"`
	} `json:"work"`
	ConfigurationRevisions []struct {
		Revision   int64          `json:"revision"`
		ContextKey WorkLogicalKey `json:"contextKey"`
	} `json:"configurationRevisions"`
	Operations  []ArchivedWorkOperation   `json:"operations"`
	Idempotency []ArchivedWorkIdempotency `json:"idempotency"`
}

type WorkImagePlatform struct {
	Os           string          `json:"os"`
	Architecture string          `json:"architecture"`
	Variant      json.RawMessage `json:"variant"`
}

type WorkImportBindings struct {
	Models  map[string]json.RawMessage `json:"models"`
	Secrets map[string]json.RawMessage `json:"secrets"`
}

type WorkImportProvenance struct {
	SourcePackageDigest WorkBlobDigest `json:"sourcePackageDigest"`
	ImportOperationId   ResourceId     `json:"importOperationId"`
	OperationMap        []struct {
		SourceOperationId ResourceId `json:"sourceOperationId"`
		OperationId       ResourceId `json:"operationId"`
	} `json:"operationMap"`
}

type WorkLogicalKey string

type WorkReadiness struct {
	Identity                WorkRuntimeIdentity `json:"identity"`
	ActiveRevision          int64               `json:"activeRevision"`
	State                   string              `json:"state"`
	ObservedAt              Timestamp           `json:"observedAt"`
	LoadedSkillIds          []ResourceId        `json:"loadedSkillIds"`
	UnavailableMcpServerIds []string            `json:"unavailableMcpServerIds"`
}

type WorkRuntimeIdentity struct {
	InstallationId ResourceId `json:"installationId"`
	WorkId         ResourceId `json:"workId"`
	Generation     int64      `json:"generation"`
}

type WorkSkillState struct {
	Desired      SkillSelection    `json:"desired"`
	Active       SkillSelection    `json:"active"`
	PendingApply bool              `json:"pendingApply"`
	Runtime      RuntimeSkillState `json:"runtime"`
}

type WorkSnapshotError struct {
	Code    string        `json:"code"`
	Message string        `json:"message"`
	Field   Field[string] `json:"field,omitzero"`
}

type WorkSnapshot struct {
	WorkId      ResourceId      `json:"workId"`
	SnapshotId  ResourceId      `json:"snapshotId"`
	OperationId ResourceId      `json:"operationId"`
	State       OperationState  `json:"state"`
	Digest      json.RawMessage `json:"digest"`
	Size        json.RawMessage `json:"size"`
	ExpiresAt   json.RawMessage `json:"expiresAt"`
	Error       json.RawMessage `json:"error"`
}

type WorkSourceIdentityMap struct {
	Version      float64    `json:"version"`
	SourceWorkId ResourceId `json:"sourceWorkId"`
	Contexts     []struct {
		SourceId ResourceId     `json:"sourceId"`
		Key      WorkLogicalKey `json:"key"`
	} `json:"contexts"`
	Services []struct {
		SourceId ResourceId     `json:"sourceId"`
		Key      WorkLogicalKey `json:"key"`
	} `json:"services"`
	Operations []struct {
		SourceId ResourceId     `json:"sourceId"`
		Key      WorkLogicalKey `json:"key"`
	} `json:"operations"`
}

type WorkToolPolicyKey string
